### ISSUE TITLE
Make -S Option available in sudo.py module

### ISSUE THREAD

**Issue by maxhenze** [dw/mitogen#108]
Make -S Option available in sudo.py module

**Comment by dw** [comment]
Hi max,

Please try now. Presently sudo always starts with a its own private TTY, so these options passed through by shouldn't have any effect.

Stupidly I'd been testing sudo with -HE ever since adding support for sudo_flags, without realizing Ansible's own set of flags were causing breakage!

**Comment by maxhenze** [comment]
works like a charm, thank you for your quick response
