### ISSUE TITLE
Entrypoint Suggestions for Development

### ISSUE THREAD

**Issue by themanifold** [dw/mitogen#115]
Two things I'd like to say:

1. You're doing a great job and I hope your kickstarter gets fully funded, and reaches its stretch goals.
2. As a intermediate-proficient python coder, I've been looking for a project to contribute to and I really like what mitogen is trying to achieve. In light of this:
    - Could I suggest that you create some issues that detail features you'd like to implement, along with level of difficulty. This would provide a great entrypoint for people who want to contribute but are unsure how to being (I have this feeling a lot when I look at open-source projects). 
    - I know LibreOffice follows this model to some success - arguably they need this a lot more given their monstrous codebase.

Example tickets could be things that have been bugging you but that you have not have the bandwidth to do: `[Easy] Tidy up foo.py`

Moderate difficulty tickets: `[Moderate] Refactor bar.py`

Difficult tickets: `[Hard] Add support for FTL in foofoo.py`

**Comment by moreati** [comment]
@themanifold welcome to the project. I think David is a bit overwhelmed at the moment. In the meantime there are 2 tickets tagged as [EASY](https://github.com/dw/mitogen/issues?q=is%3Aissue+is%3Aopen+label%3AEASY), I've not looked at them personally though.

**Comment by moreati** [comment]
#119 might also be a good starter

**Comment by dw** [comment]
Hi @themanifold, thanks for your kind words! There are quite a few EASY tickets now (although, again, some of them may not really be so easy), and soon I will start moving docstrings back out of Sphinx and into the code, to make it far more palatable to new contributors.

Feel free to comment on any of the bugs if you need a hand, and once again, thanks!
