### ISSUE TITLE
Place to Congregate

### ISSUE THREAD

**Issue by themanifold** [dw/mitogen#116]
I don't really know if this is the right place, but I think that mitogen could benefit from some kind of community where we can chat a bit about what's going on.

For example: gitter, discord, reddit, slack, etc.

**Comment by dw** [comment]
Hi there :)  I idle in the (currently empty) \#mitogen channel on Freenode. Most likely won't be able to dish out easy tickets for at least a few days. There is an "easy" label already - those tickets need better descriptions and I'm not sure they really qualify as easy.

Currently I'm firefighting a bunch of early bugs, this is going to take time :)  Thanks for your interest!
