### ISSUE TITLE
Permission denied in /tmp/ansible-mitogen-tmp-*

### ISSUE THREAD

**Issue by stefangweichinger** [dw/mitogen#118]
Tried to boil it down:

```
$ cat test_script.yml 
---

- name: saytrue
  hosts: tx100.local
  become: True

  tasks:

    - name: run script saytrue
      script: saytrue

$ cat saytrue 
#!/bin/bash
/bin/true
````

fails with

````
fatal: [tx100.local]: FAILED! => {
    "changed": true, 
    "msg": "non-zero return code", 
    "rc": 126, 
    "stderr": "/bin/sh: 1: /tmp/ansible-mitogen-tmp-fLfQCp/saytrue: Permission denied\n", 
    "stdout": "", 
    "stdout_lines": []
}
````

[test.log](https://github.com/dw/mitogen/files/1793444/test.log)

**Comment by dw** [comment]
Missing chmod +x, I know exactly what's broken. 5 minutes!

**Comment by dw** [comment]
Am I right in saying that on the controller, the script was marked executable?

**Comment by stefangweichinger** [comment]
no:

$ ls -l saytrue 
-rw-rw-r-- 1 sgw sgw 22  8. Mär 15:12 saytrue

**Comment by drybjed** [comment]
Yes, at least in the case of the script from the `debops.sshd` role.

**Comment by stefangweichinger** [comment]
yes:

-rwxrwxr-x. 1 sgw sgw 1170 21. Feb 16:25 dpkg-state

But both fail, btw ;-)

**Comment by dw** [comment]
Thanks for the report!

**Comment by stefangweichinger** [comment]
works now. thanks for the fix.
