### ISSUE TITLE
SSH connections time out when you need to accept a fingerprint

### ISSUE THREAD

**Issue by boxed** [dw/mitogen#134]
I had weird problems getting mitogen to work when testing it out, one issue was incorrect documentation (PR sent!) but the other was that I tried to connect to MACHINE2 via MACHINE1 but I didn't have MACHINE2 in authorized_hosts. After doing this myself:

```
[username@MACHINE1 ~]$ ssh MACHINE2
The authenticity of host 'MACHINE2 (XX.XX.XX.XX)' can't be established.
RSA key fingerprint is [redacted]
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '[redacted]' (RSA) to the list of known hosts.
```

mitogen connected fine.

**Comment by dw** [comment]
Related issue: #127, but there is a fix committed on Saturday (af25def01f2175a88eb5f1c608124b66ecec5cad) that should mean you didn't experience this. So there is additionally a problem with the current fix, assuming you're using an up-to-date extension
