### ISSUE TITLE
TimeoutError: read timed out

### ISSUE THREAD

**Issue by agates** [dw/mitogen#141]
Hi,

I'm testing a very long playbook with 100s of tasks that can take more than 1.5 hours to execute against 4 servers (Basic A1 (1 vcpu, 1.75 GB memory) on Azure).  Both the ansible host and targets are CentOS 7 running in Azure.  The target servers are very slow, and used for testing purposes only.

Unfortunately, when running the playbook with mitogen it doesn't get very far.  It appears to time out after sudoing.  See [mitogen_output.txt](https://github.com/dw/mitogen/files/1808535/mitogen_output.txt).

**Comment by dw** [comment]
Related upstream discussion of how timeouts should work: https://github.com/ansible/ansible/issues/14426

Have you tweaked the [timeout parameter](http://docs.ansible.com/ansible/latest/intro_configuration.html#timeout) in ansible.cfg up from its default of 10 seconds? I'd really wish this was the issue -- you do say the boxes are incredibly slow :)

Meanwhile I have just pushed some changes to respect the timeout parameter in the sudo case, so if this was the issue, it should be solved now.

Those boxes would need to be /really/ overloaded for Python to take more than 10 seconds to run the simple -c script on the sudo command line, so I don't think this is the real problem. Going to look for ways to pad out logging a little more to try and help catch the real cause

**Comment by agates** [comment]
I did have the timeout setting set to 300 seconds instead of 10 seconds just to be sure.  They really are slow :).

The script seems to get further this time, with a different error:
`CallError: exceptions.TypeError: iter_read() got an unexpected keyword argument 'display_on_failure'`

See [mitogen_output-sudo_timeout.txt](https://github.com/dw/mitogen/files/1811744/mitogen_output-sudo_timeout.txt)

**Comment by dw** [comment]
Damn, so dumb. Reference to some code I haven't checked in yet (multiple changes, single pair of hands!). I've pushed a fix

**Comment by agates** [comment]
I believe the issue is resolved!

The runtime was reduced from 1.5 hours on 4 servers to just under 3 minutes.

Thanks!

**Comment by dw** [comment]
Thanks so much for the timing report! These quotes drive a great deal of interest in the project :)  All the best!

**Comment by dw** [comment]
Can you tell me a little more about your workload in those playbooks. I'm guessing lots of big with_items loops. But a general description would be very useful. I need to update the docs at some point so expectations can be carefully set, and avoid people wasting their time on the extension when it won't help them

**Comment by agates** [comment]
This specific playbook is around [security hardening](https://www.cisecurity.org/cis-benchmarks/).  Lots of very basic tasks -- ini_file, lininfile, blockinfile, shell, command, copy, file, service, yum, user, getent, replace -- many of which are combined with with_items.
