### ISSUE TITLE
RFC: docstrings

### ISSUE THREAD

**Issue by dw** [dw/mitogen#160]
In favour of removal:

* Can finally eliminate minimize_source()
* Easy to minimize wire footprint, even for non core.py modules that don't get minimize_source() treatment just now

Cons of removal:

* Code looks ugly and unprofessional
* Pain in the ass for new contributors to understand any of the code
* Pain in the ass to keep Sphinx equivalents in sync, and no good place in the documentation for all kinds of random internal-only methods.

First alternative idea:

* Just accept source manipulation is a thing, because it lets us have our cake (wire footprint) and eat it (readable source).
* Have ModuleResponder scan for ``MITOGEN_MINIMIZE_SAFE = True`` or similar, and respond to that by doing horrible things only to the source of modules that have explicitly elected for such treatment. The reason it needs to be opt-in is because, even if it weren't for the code style-sensitive regexes, there is a /lot/ of code that introspects ``__doc__`` to implement behaviours of some sort or other (simple example: doctest) 
* Sleep better at night perhaps by building something (hopefully speedy) around the ``parser`` module, to avoid all those insane regexes.

@moreati? I've a feeling I know which way you'll swing already :)

**Comment by moreati** [comment]
> @moreati? I've a feeling I know which way you'll swing already :)

Cake please. +1 to keep docstrings, and either accept the overhead or use a stripper/minifier that is based on parsing/tokenising.

For reference these are the numbers with and without `minimize_source`

```
:~/src/mitogen p-p-p-pick-us-a-pickle(+140/-45)+*± python preamble_size2.py 
SSH command size: 417
Preamble size: 9297 (9.08KiB)
     Module        Original       Minimized       Compressed   
                Bytes  KiB  %    Bytes  KiB  %    Bytes  KiB  %   
mitogen.master  24070 23.5  100  15332 15.0 63.7   4743  4.6 19.7
mitogen.parent  18835 18.4  100  12834 12.5 68.1   4196  4.1 22.3
mitogen.ssh      4986  4.9  100   2788  2.7 55.9   1028  1.0 20.6
mitogen.sudo     6224  6.1  100   3054  3.0 49.1   1093  1.1 17.6
mitogen.fakessh 11588 11.3  100   7591  7.4 65.5   2518  2.5 21.7

:~/src/mitogen p-p-p-pick-us-a-pickle(+140/-45)+*± python preamble_size2.py 
SSH command size: 417
Preamble size: 9297 (9.08KiB)
     Module        Original       Minimized       Compressed   
                Bytes  KiB  %    Bytes  KiB  %    Bytes  KiB  %   
mitogen.master  24070 23.5  100  24070 23.5 100.0   7286  7.1 30.3
mitogen.parent  18835 18.4  100  18835 18.4 100.0   6164  6.0 32.7
mitogen.ssh      4986  4.9  100   4986  4.9 100.0   1907  1.9 38.2
mitogen.sudo     6224  6.1  100   6224  6.1 100.0   2259  2.2 36.3
mitogen.fakessh 11588 11.3  100  11588 11.3 100.0   3972  3.9 34.3
```

**Comment by moreati** [comment]
The 2 principal Python minifiers appear to be [minipy](https://github.com/gareth-rees/minipy) (uses `ast`) and [pyminifier](https://github.com/liftoff/pyminifier) (uses `tokenise`). Both have a GPL 3 license.

**Comment by dw** [comment]
Neither of these support preserving line numbers :/ I'll have a scan about for something else. ISTR Google App Engine libraries at one point used some tool of theirs to strip files while preserving line numbers, will see if I can find it.

**Comment by moreati** [comment]
I looked for modules that extend AST, the following look promising
- https://pyp.org/project/astor
- https://pypi.org/project/astunparse
- https://pypi.org/project/baron/ or https://pypi.org/project/redbaron/
- https://pypi.org/project/codegen

**Comment by moreati** [comment]
I'll look further into these over the weekend

**Comment by dw** [comment]
Please pay attention to startup time :) would prefer a regex than 300ms
burnt per invocation etc

**Comment by moreati** [comment]
I tried using `tokenize`. It's closer to correct, but it's 8.9 ms, vs 0.2 ms for the regex.

```
$ python -mperf timeit -s"import mitogen.parent, inspect, strip; s=inspect.getsource(mitogen.parent)" "strip.foo(s)"
.....................
Mean +- std dev: 8.92 ms +- 0.33 ms
$ python -mperf timeit -s"import mitogen.parent, inspect, strip; s=inspect.getsource(mitogen.parent)" "mitogen.parent.minimize_source(s)"
.....................
Mean +- std dev: 238 us +- 18 us
```

```python
BLOCK_KEYWORDS = (
    'class',
    'def',
    'for',
    'if',
    'elif',
    'else',
    'try',
    'except',
    'finally',
    'while',
    'with',
)

def foo(s):
    f = cStringIO.StringIO(source)
    tokens = tokenize.generate_tokens(f.readline)
    out = ""
    block_start = True
    block_type = 'module'
    prev_end_row = 0
    prev_end_col = 0
    for tok_type, token, (start_row, start_col), (end_row, end_col), _ in tokens:
        if prev_end_row < start_row:
            prev_end_col = 0

        if tok_type == tokenize.INDENT:
            block_start = True
        elif tok_type == tokenize.NEWLINE:
            block_start = False
        elif tok_type == tokenize.NAME and token in BLOCK_KEYWORDS:
            block_type = token

        if tok_type in (tokenize.NL, tokenize.NEWLINE):
            out += "\n"
        elif tok_type == tokenize.STRING and block_start and block_type in BLOCK_KEYWORDS[:2]:
            out += "\n" * (end_row - start_row)
        elif tok_type != tokenize.COMMENT or start_row < 3:
            out += "*" * (start_col - prev_end_col) + token

        prev_end_col = end_col
        prev_end_row = end_row

    return out
```

**Comment by dw** [comment]
9ms isn't bad if we can cache the result! Assuming this transform is only applied to Mitogen modules, then worst case it adds ~50ms to startup time. It's pretty expensive, but it's at your discretion which route to go.. that's still a pretty minor hit for a nice clean non-regex solution

**Comment by moreati** [comment]
Damn it. I thought I had a nice way of combingin `tokenize` and `ast` to find docstrings, but https://bugs.python.org/issue18370 means all triple quoted strings have the line/column offsets wrong.

**Comment by moreati** [comment]
Any reason to keep this open?

**Comment by dw** [comment]
Whups :) Horay!
