### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'endswith' in copy task

### ISSUE THREAD

**Issue by wezm** [dw/mitogen#177]
I have a task as follows that's failing with mitogen but working with the default strategy:

```
- name: copy repo configs
  copy: src={{ item }} dest=/usr/local/etc/pkg/repos/{{ item }} mode=0644
  with_items:
    - FreeBSD.conf
    - poudriere.conf
```

This is the output when running with `-vvv`

[pid 27067] 21:46:18.397137 D ansible_mitogen.mixins: _make_tmp_path(remote_user=None)
[pid 27067] 21:46:18.398497 D mitogen: unix.connect(path='/tmp/mitogen_unix_QGMkXF')
[pid 27067] 21:46:18.399020 D mitogen: unix.connect(): local ID is 1010, remote is 0
[pid 27067] 21:46:18.401303 D mitogen: Context(3, u'ssh.varnish.bsd-ci.local.sudo.root').call_async(<function mkdtemp at 0x7fab8ab74938>, *(), **{'prefix': 'ansible-mitogen-tmp-'})
[pid 27067] 21:46:18.402934 D ansible_mitogen.connection: Call mkdtemp() took 5 ms
[pid 27067] 21:46:18.403494 D ansible_mitogen.mixins: _remove_expand_user(u'/usr/local/etc/pkg/repos/FreeBSD.conf', sudoable=True)
[pid 27067] 21:46:18.404055 D mitogen: Context(3, u'ssh.varnish.bsd-ci.local.sudo.root').call_async(<function run_module at 0x7fab858c60c8>, *('ansible.modules.files.stat',), **{'args': {'_ansible_version': '2.5.0', 'follow': False, '_ansible_selinux_special_fs': ['fuse', 'nfs', 'vboxsf', 'ramfs', '9p'], '_ansible_no_log': False, '_ansible_module_name': 'stat', '_ansible_verbosity': 3, '_ansible_syslog_facility': u'LOG_USER', '_ansible_socket': None, 'checksum_algo': 'sha1', '_ansible_diff': False, 'get_checksum': True, '_ansible_debug': False, '_ansible_shell_executable': u'/bin/sh', '_ansible_check_mode': False, 'path': u'/usr/local/etc/pkg/repos/FreeBSD.conf', '_ansible_tmpdir': None}, 'env': {}})
[pid 27004] 21:46:18.406152 D mitogen.ctx.ssh.varnish.bsd-ci.local: mitogen: ModuleForwarder(Router(Broker(0x8007fd190)))._on_get_module(Message(2, 3, 3, 100, 0, 'ansible.modules.files.stat'..26))
[pid 27004] 21:46:18.406366 D mitogen: ModuleResponder(Router(Broker(0x7fab85850990)))._on_get_module('ansible.modules.files.stat')
[pid 27004] 21:46:18.406556 D mitogen: pkgutil._get_module_via_pkgutil('ansible.modules.files.stat') -> <pkgutil.ImpLoader instance at 0x7fab8401c2d8>
[pid 27004] 21:46:18.409979 D mitogen: _send_load_module(mitogen.ssh.Stream(u'ssh.varnish.bsd-ci.local'), 'ansible.modules.files.stat')
[pid 27004] 21:46:18.412241 D mitogen.ctx.ssh.varnish.bsd-ci.local: mitogen: ModuleForwarder(Router(Broker(0x8007fd190)))._on_get_module(): sending 'ansible.modules.files.stat'
[pid 27067] 21:46:18.416645 D ansible_mitogen.connection: Call run_module('ansible.modules.files.stat',) took 12 ms
[pid 27067] 21:46:18.417478 D mitogen: mitogen.core.Stream('unix_listener.27004').on_disconnect()
[pid 27067] 21:46:18.417712 D mitogen: Waker(Broker(0x7fab84fb0e10) rfd=13, wfd=14).on_disconnect()
[pid 27004] 21:46:18.417739 D mitogen: mitogen.core.Stream('unix_client.27067').on_disconnect()
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 104, in run
    item_results = self._run_loop(items)
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 322, in _run_loop
    res = self._execute(variables=task_vars)
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 554, in _execute
    result = self._handler.run(task_vars=variables)
  File "/home/wmoore/Projects/bsd-ci/infrastructure/ansible/plugins/mitogen/ansible_mitogen/mixins.py", line 128, in run
    return super(ActionModuleMixin, self).run(tmp, task_vars)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/copy.py", line 494, in run
    module_return = self._copy_file(source_full, source_rel, content, content_tempfile, dest, task_vars)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/copy.py", line 261, in _copy_file
    tmp_src = self._connection._shell.join_path(self._connection._shell.tmpdir, 'source')
  File "/usr/lib/python2.7/site-packages/ansible/plugins/shell/__init__.py", line 83, in join_path
    return os.path.join(*args)
  File "/usr/lib/python2.7/posixpath.py", line 70, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'

fatal: [varnish.bsd-ci.local]: FAILED! => {
    "msg": "Unexpected failure during module execution.", 
    "stdout": ""
}
	to retry, use: --limit @/home/wmoore/Projects/bsd-ci/infrastructure/ansible/plays/base.retry

PLAY RECAP ************************************************************************************************************
varnish.bsd-ci.local       : ok=13   changed=0    unreachable=0    failed=1   

[pid 27004] 21:46:18.462418 E mitogen: mitogen.service.Pool(0x7fab85850f50, size=16, th='mitogen.service.Pool.7fab85850f50.worker-2'): channel or latch closed, exitting: None
[pid 27004] 21:46:18.462649 E mitogen: mitogen.service.Pool(0x7fab85850f50, size=16, th='mitogen.service.Pool.7fab85850f50.worker-3'): channel or latch closed, exitting: None
[pid 27004] 21:46:18.462776 E mitogen: mitogen.service.Pool(0x7fab85850f50, size=16, th='mitogen.service.Pool.7fab85850f50.worker-5'): channel or latch closed, exitting: None
[pid 27004] 21:46:18.462878 E mitogen: mitogen.service.Pool(0x7fab85850f50, size=16, th='mitogen.service.Pool.7fab85850f50.worker-7'): channel or latch closed, exitting: None
[pid 27004] 21:46:18.462916 E mitogen: mitogen.service.Pool(0x7fab85850f50, size=16, th='mitogen.service.Pool.7fab85850f50.worker-6'): channel or latch closed, exitting: None
[pid 27004] 21:46:18.463068 E mitogen: mitogen.service.Pool(0x7fab85850f50, size=16, th='mitogen.service.Pool.7fab85850f50.worker-4'): channel or latch closed, exitting: None
[pid 27004] 21:46:18.463212 E mitogen: mitogen.service.Pool(0x7fab85850f50, size=16, th='mitogen.service.Pool.7fab85850f50.worker-10'): channel or latch closed, exitting: None
[pid 27004] 21:46:18.463345 E mitogen: mitogen.service.Pool(0x7fab85850f50, size=16, th='mitogen.service.Pool.7fab85850f50.worker-11'): channel or latch closed, exitting: None
[pid 27004] 21:46:18.463405 E mitogen: mitogen.service.Pool(0x7fab85850f50, size=16, th='mitogen.service.Pool.7fab85850f50.worker-13'): channel or latch closed, exitting: None
[pid 27004] 21:46:18.463539 E mitogen: mitogen.service.Pool(0x7fab85850f50, size=16, th='mitogen.service.Pool.7fab85850f50.worker-12'): channel or latch closed, exitting: None
[pid 27004] 21:46:18.463602 E mitogen: mitogen.service.Pool(0x7fab85850f50, size=16, th='mitogen.service.Pool.7fab85850f50.worker-9'): channel or latch closed, exitting: None
[pid 27004] 21:46:18.463703 E mitogen: mitogen.service.Pool(0x7fab85850f50, size=16, th='mitogen.service.Pool.7fab85850f50.worker-14'): channel or latch closed, exitting: None
[pid 27004] 21:46:18.463739 E mitogen: mitogen.service.Pool(0x7fab85850f50, size=16, th='mitogen.service.Pool.7fab85850f50.worker-15'): channel or latch closed, exitting: None
[pid 27004] 21:46:18.463856 E mitogen: mitogen.service.Pool(0x7fab85850f50, size=16, th='mitogen.service.Pool.7fab85850f50.worker-8'): channel or latch closed, exitting: None
[pid 27004] 21:46:18.463906 E mitogen: mitogen.service.Pool(0x7fab85850f50, size=16, th='mitogen.service.Pool.7fab85850f50.worker-1'): channel or latch closed, exitting: None
[pid 27004] 21:46:18.463947 E mitogen: mitogen.service.Pool(0x7fab85850f50, size=16, th='mitogen.service.Pool.7fab85850f50.worker-0'): channel or latch closed, exitting: None
[pid 27004] 21:46:18.465039 D mitogen: <mitogen.unix.Listener object at 0x7fab85850e10>.on_disconnect()
[pid 27004] 21:46:18.465241 D mitogen: Waker(Broker(0x7fab85850990) rfd=8, wfd=10).on_disconnect()
[pid 27004] 21:46:18.465390 D mitogen: mitogen.ssh.Stream(u'ssh.varnish.bsd-ci.local') closing CALL_FUNCTION channel
[pid 27004] 21:46:18.466743 E mitogen: Router(Broker(0x7fab85850990)): invalid handle: Message(0, 2, 2, 102, 0, 'mitogen\x0010\x00ModuleForwarder(Router(Broker(0x8007fd1'..78)
[pid 27004] 21:46:18.467013 E mitogen: Router(Broker(0x7fab85850990)): invalid handle: Message(0, 2, 2, 102, 0, 'mitogen\x0010\x00Waker(Broker(0x8007fd190) rfd=3, wfd=4)'..66)
[pid 27004] 21:46:18.467149 E mitogen: Router(Broker(0x7fab85850990)): invalid handle: Message(0, 2, 2, 102, 0, "mitogen\x0010\x00mitogen.sudo.Stream(u'sudo.root') closi"..74)
[pid 27004] 21:46:18.467241 E mitogen: Router(Broker(0x7fab85850990)): invalid handle: Message(0, 2, 2, 102, 0, 'mitogen\x0010\x00<IoLogger stdout>.on_disconnect()'..44)
[pid 27004] 21:46:18.467348 E mitogen: Router(Broker(0x7fab85850990)): invalid handle: Message(0, 2, 2, 102, 0, 'mitogen\x0010\x00<IoLogger stderr>.on_disconnect()'..44)
[pid 27004] 21:46:18.468409 E mitogen: Router(Broker(0x7fab85850990)): invalid handle: Message(0, 3, 3, 102, 0, 'mitogen\x0010\x00Waker(Broker(0x8007fe150) rfd=3, wfd=4)'..66)
[pid 27004] 21:46:18.472070 D mitogen: mitogen.ssh.Stream(u'ssh.varnish.bsd-ci.local'): child process exit status was 65280
[pid 27004] 21:46:18.472256 D mitogen: mitogen.ssh.Stream(u'ssh.varnish.bsd-ci.local').on_disconnect()
[pid 27004] 21:46:18.472421 D mitogen: mitogen.ssh.Stream(u'ssh.varnish.bsd-ci.local') is gone; propagating DEL_ROUTE for set([2, 3])
[pid 27004] 21:46:18.472524 D mitogen: Router(Broker(0x7fab85850990)).del_route(2)
[pid 27004] 21:46:18.472652 D mitogen: Router(Broker(0x7fab85850990)).del_route(3)

**Comment by dw** [comment]
Looks like tmpdir isn't being set, I'm just off a long-haul flight today and pretty knackered, should be easy to repro this tomorrow. Most likely a missing return statement (or assignment) somewhere in the mixins.py overrides, tmp handling is a little different in Mitogen compared to vanilla

**Comment by dw** [comment]
Yep.. magical side effects :)  If you don't call the function that returns the shell snippet to generate a temp dir, copy module messes up. Give me ~20 minutes, need to fix up temp file handling in a few places to fix this

**Comment by dw** [comment]
Still working on this. Ansible's temp file handling is a fiddly mess

**Comment by dw** [comment]
Thanks for reporting. Fingers crossed this doesn't regress some other functionality.. trying to get all the big ticket items done before working on regression tests. Meanwhile, all these issues contribute to those tests. :)

Thanks again, and sorry for the delay!

**Comment by wezm** [comment]
Thank you, and no need to apologise for any delay. I'm in no rush. :-)
