### ISSUE TITLE
Comprehensive integration tests.

### ISSUE THREAD

**Issue by dw** [dw/mitogen#21]

**Comment by moreati** [comment]
I've been trying to add [Tox](https://tox.readthedocs.io/en/latest/) to the test suite. So we can run the tests with multiple versions of Python. I'm forced to conclude this is impossible for Python 2.4, as long as docker-py is used. docker-py requires requests, which has never supported Python 2.4.

**Comment by dw** [comment]
I think at this point, I'm happy with the "integration" part of integration tests. The next problem, especially when it comes to Ansible, is more selective tests.

I'm going to cautiously suggest Mitogen's testing is doing what it's supposed to. There have been a relatively small (<5) number of regressions across 7 releases, and that seems more than reasonable given the size of the project

Will revisit this if there is some tremendous screw up, but most of the point of testing is to create confidence, and that confidence exists, so it seems the job is done
