### ISSUE TITLE
puppet won't run when we activate mitogen

### ISSUE THREAD

**Issue by thatsk** [dw/mitogen#261]
puppet won't run when we activated in ansible configuration.

It can skip the task and it shows failed tasks

**Comment by dw** [comment]
Hi there,

Please provide more information:

* What version of Ansible are you using?
* Is Puppet being run by Ansible, or is Ansible being run by Puppet?
* Please provide logs of Ansible running with "-vvv" specified on the command line

**Comment by dw** [comment]
Please reopen when you have more information. Thanks

**Comment by thatsk** [comment]
ansible 2.6.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]



The logs with -vvvv:-
[pid 23968] 09:17:12.099210 D ansible_mitogen.planner: BinaryPlanner() rejected u'command'
[pid 23968] 09:17:12.099892 D ansible_mitogen.planner: NewStylePlanner() accepted u'command' (filename '/usr/lib/python2.7/site-packages/ansible/modules/commands/command.py')
[pid 23968] 09:17:12.101282 D mitogen: unix.connect(path='/tmp/mitogen_unix_IkHPES')
[pid 23968] 09:17:12.101994 D mitogen: unix.connect(): local ID is 1004, remote is 0
[pid 23929] 09:17:12.104132 D mitogen: mitogen.ssh.Stream('default').connect()
[pid 23929] 09:17:12.244151 D mitogen: hybrid_tty_create_child() pid=23971 stdio=63, tty=40, cmd: "ssh" "-o" "Compression yes" "-o" "ServerAliveInterval 15" "-o" "ServerAliveCountMax 3" "-o" "StrictHostKeyChecking yes" "-C" "-o" "ControlMaster=auto" "-o" "ControlPersist=60s" "svcar01p1.ci-cp.dev.smf1.mobitv" "/usr/bin/python" "-c" "'import codecs,os,sys;_=codecs.decode;exec(_(_(\"eNpd0MFqhDAQBuBzfYreJmFDSHRZWEFokdK7h3poS9E1lrCahFE3bZ++WVxo7C3f/JMZkorVhZ24004RmiDzkXR/H9BbPBOaJ3fh3C0uJYJJIeifKxYLQypXnwY7KVLFwBh1DL9CmYtGa17hsXp+EfBeTN+h+KVOy9y0g1p7AgeyDdiWOyCjnu2nMjlaOz+cF9MMXJseGz6h4tPYSz7aVs+XPM2O6ZECTcJoj3pWRDJ4KsWbCbWy+CDXT+isUyY8HbAFylE1HZHykB4ogx/t1su3ppqBh/Ant2FlnPltBvt9lmVh0a78v15e1/8CsDR/dQ==\".encode(),\"base64\"),\"zip\"))'"
[pid 23929] 09:17:12.245553 D mitogen: mitogen.ssh.Stream('local.23971').connect(): child process stdin/stdout=63
[pid 23929] 09:17:12.297065 D mitogen: mitogen.ssh.Stream('local.23971'): received 'This is a private system, restricted to authorized individuals.\nThis system is subject to monitoring.\nUnauthorized users, access, and/or modification will be prosecuted.\n'
[pid 23929] 09:17:12.336750 D mitogen: mitogen.ssh.Stream('local.23971'): received 'EC0\n'
[pid 23929] 09:17:12.337089 D mitogen: mitogen.ssh.Stream('local.23971')._ec0_received()
[pid 23929] 09:17:12.347070 D mitogen: Context(1005, u'ssh.svcar01p1.ci-cp.dev.smf1.mobitv').call_async(<function expanduser at 0x7fb5efb3e938>, *('~',), **{})
[pid 23929] 09:17:12.381790 D mitogen: Context(1005, u'ssh.svcar01p1.ci-cp.dev.smf1.mobitv').call_async(<function init_child at 0x25fb578>, *(), **{})
[pid 23929] 09:17:12.383767 D mitogen: ModuleResponder(Router(Broker(0x2606a90)))._on_get_module('ansible_mitogen')
[pid 23929] 09:17:12.384010 D mitogen: _send_load_module(mitogen.ssh.Stream(u'ssh.svcar01p1.ci-cp.dev.smf1.mobitv'), 'ansible_mitogen')
[pid 23968] 09:17:12.385325 D mitogen: Context(1005, u'ssh.svcar01p1.ci-cp.dev.smf1.mobitv').call_async(<function run_module at 0x25fb668>, *({'should_fork': False, 'emulate_tty': True, 'module_utils': [], 'args': {'_ansible_version': '2.6.0', u'warn': False, '_ansible_selinux_special_fs': ['fuse', 'nfs', 'vboxsf', 'ramfs', '9p'], '_ansible_no_log': False, '_ansible_module_name': u'command', u'_raw_params': u'rpm -q mobi-ssc-paytv-auth-adapter-5.37.4-201807021120.d62c09d.noarch', '_ansible_verbosity': 3, '_ansible_keep_remote_files': False, '_ansible_syslog_facility': u'LOG_USER', '_ansible_socket': None, '_ansible_diff': False, '_ansible_remote_tmp': u'~/.ansible/tmp', '_ansible_shell_executable': u'/bin/sh', '_ansible_check_mode': False, '_ansible_tmpdir': None, '_ansible_debug': False}, 'module': u'command', 'service_context': Context(0, None), 'wrap_async': 0, 'env': {}, 'interpreter': None, 'path': '/usr/lib/python2.7/site-packages/ansible/modules/commands/command.py', 'interpreter_arg': None, 'runner_name': 'NewStyleRunner'},), **{})
[pid 23929] 09:17:12.386836 D mitogen: ModuleResponder(Router(Broker(0x2606a90)))._on_get_module('ansible_mitogen.target')
[pid 23929] 09:17:12.387101 D mitogen: _send_load_module(mitogen.ssh.Stream(u'ssh.svcar01p1.ci-cp.dev.smf1.mobitv'), 'ansible_mitogen.target')
[pid 23929] 09:17:12.399980 D mitogen: ModuleResponder(Router(Broker(0x2606a90)))._on_get_module('ansible')
[pid 23929] 09:17:12.400251 D mitogen: _send_load_module(mitogen.ssh.Stream(u'ssh.svcar01p1.ci-cp.dev.smf1.mobitv'), 'ansible')
[pid 23929] 09:17:12.401741 D mitogen: ModuleResponder(Router(Broker(0x2606a90)))._on_get_module('ansible.release')
[pid 23929] 09:17:12.401972 D mitogen: _send_load_module(mitogen.ssh.Stream(u'ssh.svcar01p1.ci-cp.dev.smf1.mobitv'), 'ansible.release')
[pid 23929] 09:17:12.403252 D mitogen: ModuleResponder(Router(Broker(0x2606a90)))._on_get_module('ansible.module_utils')
[pid 23929] 09:17:12.403505 D mitogen: _send_load_module(mitogen.ssh.Stream(u'ssh.svcar01p1.ci-cp.dev.smf1.mobitv'), 'ansible.module_utils')
[pid 23929] 09:17:12.404937 D mitogen: ModuleResponder(Router(Broker(0x2606a90)))._on_get_module('ansible.module_utils.json_utils')
[pid 23929] 09:17:12.405176 D mitogen: _send_load_module(mitogen.ssh.Stream(u'ssh.svcar01p1.ci-cp.dev.smf1.mobitv'), 'ansible.module_utils.json_utils')
[pid 23929] 09:17:12.406728 D mitogen: ModuleResponder(Router(Broker(0x2606a90)))._on_get_module('ansible_mitogen.runner')
[pid 23929] 09:17:12.406957 D mitogen: _send_load_module(mitogen.ssh.Stream(u'ssh.svcar01p1.ci-cp.dev.smf1.mobitv'), 'ansible_mitogen.runner')
[pid 23968] 09:17:12.410137 D ansible_mitogen.connection: Call took 24 ms: run_module({'should_fork': False, 'emulate_tty': True, 'module_utils': [], 'args': {'_ansible_version': '2.6.0', u'warn': False, '_ansible_selinux_special_fs': ['fuse', 'nfs', 'vboxsf', 'ramfs', '9p'], '_ansible_no_log': False, '_ansible_module_name': u'command', u'_raw_params': u'rpm -q mobi-ssc-paytv-auth-adapter-5.37.4-201807021120.d62c09d.noarch', '_ansible_verbosity': 3, '_ansible_keep_remote_files': False, '_ansible_syslog_facility': u'LOG_USER', '_ansible_socket': None, '_ansible_diff': False, '_ansible_remote_tmp': u'~/.ansible/tmp', '_ansible_shell_executable': u'/bin/sh', '_ansible_check_mode': False, '_ansible_tmpdir': None, '_ansible_debug': False}, 'module': u'command', 'service_context': Context(0, None), 'wrap_async': 0, 'env': {}, 'interpreter': None, 'path': '/usr/lib/python2.7/site-packages/ansible/modules/commands/command.py', 'interpreter_arg': None, 'runner_name': 'NewStyleRunner'},)
[pid 23929] 09:17:12.412875 D ansible_mitogen.services: ContextService().put(Context(1005, u'ssh.svcar01p1.ci-cp.dev.smf1.mobitv'))
[pid 23968] 09:17:12.413551 D mitogen: mitogen.core.Stream('unix_listener.23929').on_disconnect()
[pid 23968] 09:17:12.413871 D mitogen: Waker(Broker(0x262ce10) rfd=15, wfd=16).on_disconnect()
[pid 23929] 09:17:12.414749 D mitogen: mitogen.core.Stream('unix_client.23968').on_disconnect()
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 138, in run
    res = self._execute()
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 576, in _execute
    result = self._handler.run(task_vars=variables)
  File "/etc/ansible/mitogen-master/ansible_mitogen/mixins.py", line 114, in run
    return super(ActionModuleMixin, self).run(tmp, task_vars)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/command.py", line 24, in run
    results = merge_hash(results, self._execute_module(task_vars=task_vars, wrap_async=wrap_async))
  File "/etc/ansible/mitogen-master/ansible_mitogen/mixins.py", line 325, in _execute_module
    wrap_async=wrap_async,
  File "/etc/ansible/mitogen-master/ansible_mitogen/planner.py", line 390, in invoke
    planner.plan(invocation),
  File "/etc/ansible/mitogen-master/ansible_mitogen/connection.py", line 524, in call
    return self.call_async(func, *args, **kwargs).get().unpickle()
  File "/etc/ansible/mitogen-master/mitogen/core.py", line 427, in unpickle
    raise obj
CallError: exceptions.AttributeError: 'module' object has no attribute 'run_module'
  File "<stdin>", line 1858, in _dispatch_calls
  File "<stdin>", line 1845, in _dispatch_one


fatal: [svcar01p1.ci-cp.dev.smf1.mobitv]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}

NO MORE HOSTS LEFT **********************************************************************************************
        to retry, use: --limit @/etc/ansible/inventories/playbooks/common/test2.retry

**Comment by dw** [comment]
Hi there,

Can you please re-run with "MITOGEN_ROUTER_DEBUG=1" in your environment, and email me the "/tmp/mitogen.*" files created on the *target* machine. This looks really strange -- there is nothing obvious about your configuration that is broken.

Can you please also confirm the operating system of the target machine, along with the version of Python available as the "python" command when typed no the target.

Can you please confirm no "ansible_python_interpreter" setting appears as a variable in your playbook or Ansible configuration.

Sorry for the hassle, and thanks for reporting!

**Comment by dw** [comment]
My email address is dw@botanicus.net

**Comment by thatsk** [comment]
how to set MITOGEN_ROUTER_DEBUG=1 . Is it something in ansible.cfg or ?
how can check ansible_python_interpreter setting ?

**Comment by RonnyPfannschmidt** [comment]
@thatsk its a environment variable, so exporting it in the shell should do

**Comment by thatsk** [comment]
Sorry for late. I have just tested with scratch installation and configuration it works fine.
Current actual execution time                                           264.42s 4min 4sec

with pipelining and without free strategy                         233.65s 3min 89s

With mitogen and linear strategy                                    144.84s 2min 4 sec

With mitogen and free strategy                                       130.73s    2min1s


Awesome @dw cheers
