### ISSUE TITLE
TimeoutError to pfsense box

### ISSUE THREAD

**Issue by opoplawski** [dw/mitogen#268]
I'm working on some modules to modify pfsense boxes.  Trying out mitogen as well (great so far, thanks!).  Got this:
```
ERROR! [pid 16444] 10:01:08.955336 E mitogen.ctx.fork.37894: mitogen: mitogen.service.Pool(0x803af3f90, size=5, th='mitogen.service.Pool.803af3f90.worker-4'): worker 'mitogen.service.Pool.803af3f90.worker-4' crashed                                                                                                                                 
Traceback (most recent call last):
  File "master:/export/home/orion-admin/ansible-boulder/mitogen/mitogen/service.py", line 533, in _worker_main
    self._worker_run()
  File "master:/export/home/orion-admin/ansible-boulder/mitogen/mitogen/service.py", line 519, in _worker_run
    msg = self._select.get()
  File "master:/export/home/orion-admin/ansible-boulder/mitogen/mitogen/select.py", line 121, in get
    recv = self._latch.get(timeout=timeout, block=block)
  File "<stdin>", line 1172, in get
  File "<stdin>", line 1191, in _get_sleep
TimeoutError: None
```

Also have had a connection just hang.

**Comment by dw** [comment]
Hi there,

Does this reproduce 100% of the time?

Can you please let me know pfsense version, Ansible version, and host OS.

If possible, can you check if it still reproduces at commit 874c0fdc019c5abdebf9b60649381568bbb15f4a

Can you please rerun with -vvvv output, just snip the previous 50 lines or so prior to the traceback

The hung connection is almost certainly due to the crashed worker.

**Comment by opoplawski** [comment]
Not 100%, just a couple times so far.  pfsense version 2.4.2-RELEASE-p1 or 2.4.3_p1.  ansible 2.5.5.  Host os is Scientific Linux 7.5 (RHEL clone).  I'm running with the latest master of mitogen (876a82f00de3241a3649f1b8b4d76b7bd9f6c4f6).

I'll run with -vvvv for a bit now and try to reproduce.  With that I'm also starting to see messages like this:
```
ERROR! [pid 23030] 10:38:29.040025 E mitogen.ctx.fork.56454: mitogen: Router(Broker(0x80209be10)): no route for Message(0, 3020, 3020, 102, None, "mitogen\x0010\x00register(Context(8, 'parent'), mitogen."..72), my ID is 3020
```

**Comment by dw** [comment]
Ignore those, they're on the todo. They're "harmless". There is some annoying logging-related race I just haven't dug into yet

**Comment by dw** [comment]
Hi there,

I am struggling to replicate your configuration. Can you please confirm the variables you are using and the pieces below:

- You're using ansible_password to perform password authentication, at least in some cases (found a bug here already)
- You have to set ansible_python_interpreter=/usr/local/bin/python2.7

I can't get past this part, nor determine what's causing it:

````
[17:32:37 Eldil!41 ansible] cat pfsense.hosts
[all]
pfsense ansible_host=172.16.178.251 ansible_user=admin ansible_password=admin ansible_python_interpreter=/usr/local/bin/python2.7
[17:32:39 Eldil!42 ansible] ansible -m setup -i pfsense.hosts all -vvv
ansible 2.5.5
  config file = /Users/dmw/src/mitogen/tests/ansible/ansible.cfg
  configured module search path = [u'/Users/dmw/src/mitogen/tests/ansible/lib/modules']
  ansible python module location = /Users/dmw/src/mitogen/.venv/lib/python2.7/site-packages/ansible
  executable location = /Users/dmw/src/mitogen/.venv/bin/ansible
  python version = 2.7.15 (default, May  1 2018, 16:44:37) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
Using /Users/dmw/src/mitogen/tests/ansible/ansible.cfg as config file
Parsed /Users/dmw/src/mitogen/tests/ansible/pfsense.hosts inventory source with ini plugin
META: ran handlers
Using module file /Users/dmw/src/mitogen/.venv/lib/python2.7/site-packages/ansible/modules/system/setup.py
<172.16.178.251> ESTABLISH SSH CONNECTION FOR USER: admin
<172.16.178.251> SSH: EXEC sshpass -d42 ssh -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=admin -o ConnectTimeout=10 -o ControlPath=/Users/dmw/.ansible/cp/4e65638e60 172.16.178.251 '/bin/sh -c '"'"'/usr/local/bin/python2.7 && sleep 0'"'"''
<172.16.178.251> (2, '', 'Bad -c option\n')
pfsense | FAILED! => {
    "changed": false,
    "module_stderr": "Bad -c option\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 2
}
````

I tried changing ANSIBLE_EXECUTABLE to point at /bin/csh but it didn't help.

**Comment by opoplawski** [comment]
I'm using ssh pubkey authentication - in particular via a yubikey smartcard added to my ssh-agent - so that's probably how I'm avoided the sshpass issue.  Also there was a note somewhere about using paramiko to connect with password auth to avoid issues with BSD password prompts, which seemed to work for me for password auth.

I'm setting ansible_python_interpreter: /usr/local/bin/python2.7 via a group variable for the "pfsense" group that contains my pfsense boxes.

I haven't been able to reproduce with -vvvv - probably affecting some timing or something.

**Comment by dw** [comment]
Hmm.. random failure, eh? There is definitely something about the async work that I recently checked in causing this. There are 3 tickets open about random failures just now and I can't reproduce any of them :sa: 

Can you paste the output of `ansible-config dump --only-changed`  (particularly the `forks` setting)

Also how many devices are you targeting concurrently?

You might try running with `MITOGEN_ROUTER_DEBUG=1` in the environment and see if that influences the timing any -- but note, this generates /tmp file spam on every target machine, which might be a problem esp if you have to run it repeatedly to trigger it

**Comment by opoplawski** [comment]
config:
```
ANSIBLE_PIPELINING(/export/home/orion-admin/ansible-boulder/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/export/home/orion-admin/ansible-boulder/ansible.cfg) = -C -o ControlMaster=auto -
DEFAULT_BECOME(/export/home/orion-admin/ansible-boulder/ansible.cfg) = True
DEFAULT_CALLBACK_WHITELIST(/export/home/orion-admin/ansible-boulder/ansible.cfg) = ['profile_tasks'
DEFAULT_FORKS(/export/home/orion-admin/ansible-boulder/ansible.cfg) = 25
DEFAULT_GATHERING(/export/home/orion-admin/ansible-boulder/ansible.cfg) = smart
DEFAULT_HOST_LIST(/export/home/orion-admin/ansible-boulder/ansible.cfg) = [u'/export/home/orion-adm
DEFAULT_ROLES_PATH(/export/home/orion-admin/ansible-boulder/ansible.cfg) = [u'/export/home/orion-ad
DEFAULT_STRATEGY(/export/home/orion-admin/ansible-boulder/ansible.cfg) = mitogen_linear
DEFAULT_STRATEGY_PLUGIN_PATH(/export/home/orion-admin/ansible-boulder/ansible.cfg) = [u'/export/hom
PERSISTENT_CONNECT_TIMEOUT(/export/home/orion-admin/ansible-boulder/ansible.cfg) = 30
RETRY_FILES_ENABLED(/export/home/orion-admin/ansible-boulder/ansible.cfg) = False
```
At most I'm trying to access 3 devices.  2 of which are over VPN connections to remote sites.

**Comment by ssbarnea** [comment]
Interesting ticket, I am using an oversized pfsense router at home too and i am interested about using ansible with it or to use it as proxy for configuring other devices on my network. Let me know if I can help with some feedback.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by opoplawski** [comment]
@ssbarnea  - this is what I'm developing for configuring pfsense boxes with ansible - https://github.com/opoplawski/ansible-pfsense

**Comment by dw** [comment]
Hi @opoplawski!

Would it be possible for you to re-test with the latest master? During the Python 3 port I found a huge issue with targeting older Python versions in the bootstrap -- it manifested as TimeoutError.

**Comment by opoplawski** [comment]
Things are looking much better on current master, I'm going to close this.  Thanks!
