### ISSUE TITLE
Pick a nice name

### ISSUE THREAD

**Issue by dw** [dw/mitogen#27]
Given the package functionality, Mitosis seemed appropriate, but there is an unuploaded PyPI package registered with that name. @BrandonHoffman is that a dead project? Could I have it?

**Comment by BrandonHoffman** [comment]
yeah, I would be willing to release it to you. There wasent anything really posted on it. I claimed the name for another project and ended up using a different package name later on. Do you want me to add you as the owner to the package directly (if so I need your pypi username) or would you rather I just delete the project and let you claim it.

**Comment by dw** [comment]
Hi Brandon, thanks for replying :)  I settled on Mitogen in the end, which is "kinda sorta" a nicer name. Thanks again!
