### ISSUE TITLE
package: state=present generates warning with dnf on Fedora 27/28

### ISSUE THREAD

**Issue by opoplawski** [dw/mitogen#272]
Applying:
```
package: name=postfix state=present
```
to a machine with the package already installed results in:
```
[WARNING]: 
[pid 18152] 08:33:39.308784 W mitogen.ctx.ssh.HOST.sudo.root: dnf: Package postfix-2:3.2.5-2.fc27.x86_64 is already installed, skipping.
ok: [HOST]
```

**Comment by dw** [comment]
I agree it shouldn't spam the console by default, however the new visibility is quite useful. One option is to simply bury mitogen.ctx.* messages below ERROR level in -vvv output, and leave a little infrastructure in place to tweak that policy later.

There are also options to expose it for '-vv', but I'm not sure what regular Ansible's policy is for -vv.

Definitely open to opinions here :)

**Comment by opoplawski** [comment]
I'll just note that I get that output without any -v options, which definitely seems wrong to me.  I think it would be fine with some number of '-v's.

**Comment by dw** [comment]
Fix for this on master :)

**Comment by opoplawski** [comment]
Confirmed.  Thanks!
