### ISSUE TITLE
ansible breaks with "ansible_python_interpreter = /usr/bin/env python"

### ISSUE THREAD

**Issue by dw** [dw/mitogen#289]
````
180629 07:37:56 <ayaz> Pilou: Thanks. I am testing mitogen for ansible against an
          existing playbook which runs fine without it, but with mitogen, gives the
          following error: ""Child start failed: [Errno 2] No such file or directory.
          Command was: \"/usr/bin/env python\" \"-c\" \"import codecs,os,s". I've
          ensured Python exists on the target and so do modules. Without mitogen, the
          playbook and that step particularly works fine.
````

**Comment by whachoe** [comment]
i have the same issue on OSX.

**Comment by dw** [comment]
Hi there, just realized there are 2 bugs open for this :) I'll keep this one active so you get email when it's fixed. The issue is a little more nuanced than it first looked, so this will take another few days. Sorry for the delay replying and thanks for confirming the issue!

**Comment by dw** [comment]
This is now on the master branch and will make it into the next release. To be updated when a new release is made, subscribe to https://www.freelists.org/list/mitogen-announce

Thanks for reporting this!
