### ISSUE TITLE
No noticeable performance boost with Ansible 2.2.1 with mitogen alone

### ISSUE THREAD

**Issue by ayaz** [dw/mitogen#290]
I ran some benchmarks comparing a playbook run in different scenarios between Ansible 2.2.1 and Ansible 2.5.5. The performance boost claimed by mitogen was only visible with Ansible 2.5.5 but not with Ansible 2.2.1.

I have attached [benchmarks here as Google docs](https://docs.google.com/spreadsheets/d/1LVAURatP9k2pHXGabjGxMFrrDKsmTaTdnne6HAeICZs/edit#gid=0) for easy viewing. 

Please let me know if I need to provide any more details.

Host OS: Max OS X 10.11.6
Target OS: Debian 8
Host Python: 2.7.15

**Comment by dw** [comment]
Per IRC chat, I haven't forgotten about this :) But I need to get 2.6 working before looking back to 2.2, and possibly also sorting out CI, it's become sorely unmanageable due to the number of versions already.

**Comment by dw** [comment]
Hi, I'm going to close this one off -- I could spend the time supporting 2.2, but probably it is best to invest that in bugs against more recent versions :)  Thanks for reporting this!

**Comment by ayaz** [comment]
Yeah, no worries @dw. We ported our application to 2.5 in order to make use of mitogen. I also do think it is not worth the time supporting 2.2 at this stage.
