### ISSUE TITLE
wrap_connection_loader__get() takes exactly 3 arguments (1 given)

### ISSUE THREAD

**Issue by colin-mccarthy** [dw/mitogen#299]
Hello trying to run an Ansible playbook on MacOS and getting this error. 

```TASK [SHOW RUN | BEG VTY] ******************************************************************************************************************************************************************************
Wednesday 11 July 2018  14:27:22 -0400 (0:00:00.389)       0:00:00.389 ********
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: wrap_connection_loader__get() takes exactly 3 arguments (1 given)
fatal: [192.168.161.15]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}```



Here is the full repo I'm using....
https://github.com/colin-mccarthy/mitogen-test




ansible 2.6.0
  config file = /Users/colin/Desktop/mitogen-test/ansible.cfg
  configured module search path = [u'/Users/colin/.ansible/plugins/modules',      u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Oct  6 2017, 22:29:07) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]

**Comment by dw** [comment]
Hi there,

Your version of Ansible is too recent -- try any from the 2.5 series, it
should be fine. Will push a new release shortly to fix things on 2.6.

**Comment by dw** [comment]
Ah, that's not the problem! You're running network modules -- Mitogen doesn't help here, but it shouldn't break either. Give me an hour or two.

**Comment by colin-mccarthy** [comment]
Roger that, thanks!

**Comment by dw** [comment]
Hey there,

I'm having a little trouble reproducing this. Could you please re-run with "-vvv" enabled, and include the full traceback. Thanks!

**Comment by colin-mccarthy** [comment]
[vvvv.txt](https://github.com/dw/mitogen/files/2190381/vvvv.txt)

**Comment by dw** [comment]
Hi there,

I tried yesterday to set up a GNS3 test environment, but didn't get very far :)  Networking isn't really my department!

Regardless, if you try the branch available from https://github.com/dw/mitogen/archive/dmw.zip , I think you'll find your run will complete successfully now.

Once again, Mitogen can't help with network plugins -- it's designed to immediately disable itself when non-Mitogen connection types are in use.

Please let me know if this fixes the crash for you! Thanks.

**Comment by dw** [comment]
Hi there,

I'm closing this off, please feel free to reopen if it's still broken, or leave a comment to confirm.

Thanks for reporting!
