### ISSUE TITLE
command-line line 0: missing argument

### ISSUE THREAD

**Issue by DSpeichert** [dw/mitogen#304]
It seems that mitogen is producing incorrect cmd that doesn't work on MacOS. I think it is not an issue just because I use a wrapper that adds some additional args to `ssh` (although it could be). The produced command uses mixed-style options.

Error:
> "msg": "EOF on stream; last 300 bytes received: 'command-line line 0: missing argument.\\r\\n'",

Command:
> [pid 45797] 15:34:05.382614 D mitogen: hybrid_tty_create_child() pid=45811 stdio=102, tty=60, cmd: "jump-ssh-wrapper" "-l" "sre" "-o" "Compression yes" "-o" "ServerAliveInterval 15" "-o" "ServerAliveCountMax 3" "-o" "StrictHostKeyChecking no" "-o" "UserKnownHostsFile /dev/null" "-o" "GlobalKnownHostsFile /dev/null" "-C" "-o" "ControlMaster=auto" "-o" "ControlPersist=60s" "hostname-of-target" "/usr/bin/python" "-c" "'import codecs,os,sys;_=codecs.decode;exec(_(_(\"crop==\".encode(),\"base64\"),\"zip\"))'"

Should be:
> [pid 45797] 15:34:05.382614 D mitogen: hybrid_tty_create_child() pid=45811 stdio=102, tty=60, cmd: "jump-ssh-wrapper" "-l" "sre" "-o" "Compression=yes" "-o" "ServerAliveInterval=15" "-o" "ServerAliveCountMax=3" "-o" "StrictHostKeyChecking=no" "-o" "UserKnownHostsFile=/dev/null" "-o" "GlobalKnownHostsFile=/dev/null" "-C" "-o" "ControlMaster=auto" "-o" "ControlPersist=60s" "hostname-of-target" "/usr/bin/python" "-c" "'import codecs,os,sys;_=codecs.decode;exec(_(_(\"crop==\".encode(),\"base64\"),\"zip\"))'"

Notice the additional `=` for `-o` options.

Is this intentional or configurable?

**Comment by dw** [comment]
Hi there,

Both formats are valid according to ssh_config. This sounds like a quoting issue in your wrapper script. Would it be possible for you to share that? It sounds like the script is giving shell a chance to reinterpret those space characters, which likely means the base64-encoded chunk is at risk of being reinterpreted too :)

**Comment by dw** [comment]
Hi,

I played around locally here, and there is not much can be done if the wrapper script is broken -- while adding = works around the problem with the -o parameters, the Python code snippet absolutely still requires the space character to be present.

Please feel free to paste your wrapper here and I can suggest a suitable fix for you. Meanwhile I'm closing off this bug. Thanks!
