### ISSUE TITLE
How to use it?..

### ISSUE THREAD

**Issue by Oloremo** [dw/mitogen#306]
Probably a stupid question.

Env:
```
ansible 2.4.3.0
  config file = /Users/oloremo/git/ansible_behavox/ansible.cfg
  configured module search path = [u'/Users/oloremo/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/oloremo/git/tools/lib/python2.7/site-packages/ansible
  executable location = /Users/oloremo/git/tools/bin/ansible
  python version = 2.7.14 (default, Sep 25 2017, 09:54:19) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]
```

Doc states that I have to
1) Download the stable release
2) Update ansible.cfg with `strategy_plugins = /path/to/mitogen-master/ansible_mitogen/plugins/strategy`

Well, first of all, there is a `mitogen-master` vs `mitogen-stable` directory difference. So I copied it into library directory in ansible root and added the
```
strategy_plugins = ./library/strategy_plugins/mitogen-stable/plugins/strategy
```
When I try to run it I get the
```
ERROR! Unexpected Exception, this is probably a bug: No module named ansible_mitogen.loaders
```

**Comment by RyanOakes** [comment]
You sure your path is right? If you download the zip based off the install instructions and unzip, you should be left with a folder called _mitogen-stable_. If you were to move that entire folder to your library folder, your path should look something like this: 

```
strategy_plugins = ./library/mitogen-stable/ansible_mitogen/plugins/strategy
```

It looks like you gutted the _ansible_mitogen_ section of the path therefore its blowing up when trying to load the _loaders.py_ file

**Comment by Oloremo** [comment]
You're right, sorry for the noise.

**Comment by dw** [comment]
@RyanOakes first bug opened and closed while I wasn't looking! Was confused on seeing this in my mail and not in the tracker. Thanks :)
