### ISSUE TITLE
target disconnected while in `Receiver.get()`

### ISSUE THREAD

**Issue by svinota** [dw/mitogen#348]
Is there any way to interrupt `Receiver.get()` if the target gets disconnected?

**Comment by svinota** [comment]
yeah. So I:

1. create context (`ssh = router.ssh(…)`)
2. create `Receiver(…, respondent=ssh)`
3. create call, send there `Receiver.to_sender()` as an argument
4. …
5. wait for `.get().unpickle()`, get `ChannelError` in the case of disconnected channel.

Testing now, looks like working.

**Comment by dw** [comment]
Buyer beware! The core library interfaces are rough-edged to say the least :) Feel free to spam bugs for helper functions and suchlike that you may find useful.

**Comment by svinota** [comment]
Provided the context as the `respondent` to the `Receiver`, everything works perfectly, raising exceptions on both explicit disconnects and timeouts.

Do I understand correctly that it is not the default behaviour since one `Receiver` may be used in different contexts?

**Comment by dw** [comment]
It's default for regular function calls, and ideally it'd be default in more places, but Receiver is a pretty raw/overly general abstraction to begin with

**Comment by dw** [comment]
Lots of this stuff is fairly sucky right now -- for example, the ChannelError raised doesn't really tell you what is happening, even though it easily could.

I'm not averse to extra helper methods wrapping up common idioms like yours

**Comment by dw** [comment]
I've opened #348 to track more descriptive error messages.

I'm closing this as it was mostly an assistance request, however feel free to reopen if you have further queries or consider the issue a bug. Note that for quick ad-hoc questions, some users and developers are available on the [#mitogen](https://webchat.freenode.net/?channels=mitogen) channel on the FreeNode IRC network. Thanks!
