### ISSUE TITLE
Python3 related issue

### ISSUE THREAD

**Issue by svinota** [dw/mitogen#349]
Trying to run the code under python3 I get an error — see the log attached: [error.log](https://github.com/dw/mitogen/files/2315903/error.log)

The issue gets reproduced on the latest master as well.

The Python version is 3.6.5, the host system is Fedora, the target is Debian, Python versions are the same.

Under Python 2 there are no issues.

**Comment by dw** [comment]
Python 3 recently introduced this new "importer spec" business and seems it doesn't handle aliases well, or I'm not doing things right. Thanks for reporting this -- both fixes should be pretty straightforward

**Comment by dw** [comment]
Hi,

Looking at this again, it seems the main problem was the format string -- actually the case of missing get_filename() is already handled by the code. Closing this off :)

Thanks again for reporting this!

**Comment by dw** [comment]
btw, there is another bug open for that stdlib roundtrip problem -- the client should know not to ask for it whatsoever. So far it seems to be a minor nit rather than a perf showstopper, thankfully
