### ISSUE TITLE
ansible_mitogen.target: prune_tree Operation not permitted

### ISSUE THREAD

**Issue by opoplawski** [dw/mitogen#378]
Using current git master.  At the end of the play after the timings are printed I get:
```
ERROR! [pid 28488] 13:36:50.488183 E mitogen.ctx.ssh.HOST.sudo.root: ansible_mitogen.target: prune_tree(u'/tmp/ansible_mitogen_TlBgLS/worker-28606-7f0e684189d0'): [Errno 1] Operation not permitted: '/tmp/ansible_mitogen_TlBgLS/worker-28606-7f0e684189d0'
```
Host is EL7.5, ansible 2.6.4, python 2.7.5.  Target is pfsense (FreeBSD), python 2.7.14.
I'm using sudo.

The error appears to go away at debug level -vvv, and -vv doesn't give any more info than the above.

**Comment by opoplawski** [comment]
Not on every playbook - appears to depend on what tasks are run.

**Comment by opoplawski** [comment]
May only occur when there is an error in the play.

**Comment by opoplawski** [comment]
Just got it again with a successful play.  Target is EL7.5.

**Comment by dw** [comment]
0.2.3 is delayed because I had to completely rework temp file handling Sorry about this, and thanks for reporting!

**Comment by dw** [comment]
It looks like the offending call is os.rmdir(), and that error would be raised if the directory is not empty.

**Comment by dw** [comment]
Hmm :) I think this one was already fixed on my branch, temp files was re-re-re-done but had not been merged down. Please try latest master and let me know if the issue persists.
