### ISSUE TITLE
core: IO logging is too expensive

### ISSUE THREAD

**Issue by dw** [dw/mitogen#39]
Even when disabled it is still 10% of the total cost of rsync. Adding an ``_iolog = False`` in core.py and regexing all ``IOLOG.debug()`` calls to ``_iolog and IOLOG.debug()`` works, but it's a mess, and doesn't work well for other modules importing the logger.

**Comment by moreati** [comment]
`__debug__` & -O could have potential here http://www.engyrus.com/2013/03/idtkap-4-debug-and-o.html

>The -O flag is documented as removing assert instructions as though you never wrote them. But that's not all it does. It also sets a constant, `__debug__`, which is normally `True`, to `False`. The value of `__debug__` is known at compile time, so Python can use it to completely discard conditional blocks predicated on `__debug__`, just as it does with assert statements, when running with the `-O` flag. And in fact, this is exactly what Python does!

**Comment by dw** [comment]
This is a nice idea, however while modifying global state is no problem in
children, requiring -O in the master stymies integration of existing apps.
AFAIK the only way to do it for Ansible is exporting PYTHONOPTIMIZE=1,
which means it would be user-visible. :(

Another option is hacking __init__.py to hand-construct core.py, forcing
CO_OPTIMIZED in the compile() call, and paying homage to any PEP-302 hooks
installed. This seems pretty messy though, but potentially still worth it,
and we'd still end up with an environment variable to set, but not such a
bad one, as it only needs set during debugging.


David
