### ISSUE TITLE
Find a replacement CI system

### ISSUE THREAD

**Issue by dw** [dw/mitogen#390]
Travis is a wonderful go-to solution for CI, but Mitogen has testing needs greater than Travis can accommodate:

- We really want to test every combination of Ansible (2.4, 2.5, 2.6, 2.7) against every combination of Python 2.6, 2.7, 3.4, 3.5, 3.6, 3.7 host _and_ target at least once per week, and preferably much more often than that.
- Same as above but for DebOps and Mitogen's own tests. So that's 48*3 = approaching 144 configurations in total.
- There must be a set of comprehensive fast-feedback tests, probably covering the configurations in the existing Travis config (old+newest Python, oldest+newest Ansible) that complete in under 15 minutes and preferably as close to 5 minutes as possible. Slow tests rot quickly, and *ahem* especially for some people they rot obscenely quickly.
- There needs to be support for testing against FreeBSD, NetBSD, OpenBSD and Windows Subsystem for Linux at least once per week
- Code coverage and timing reports (e.g. the output of the integration tests running under [ARA](https://github.com/openstack/ara)) should be collected and kept as assets
- Ideally some kind of benchmarking facility that runs weekly could exist, but this may be a huge time sink.
- A major goal would be to have CI 100% green before merges to master are possible. Travis is simply too slow for that

Ideally all the tests could run in parallel e.g. as EC2 spot instances that are garbage collected after each run, or persist for 3-5 minutes post-run in case of a new job appearing.

I've found some systems that might suit this kind of setup:

- Azure Devops (comes with self-hosted agent support)
- Buildkite (self-hosted agent)

The principle metrics for picking a CI provider are probably:

- job latency. 5 minute waits for a job to even be scheduled is a huge no-no. Buildkite's jobs start almost instantaneously with the self-hosted agent.
- Cost. Especially if I'm picking up the infrastructure fees, some high monthly subscription would be unreasonable
- The UI must not suck. Preferably it'd support JUnit XML file rendering to display test results, IIRC even ARA supports outputting those.
   - Preferably no login required for anyone to view CI state (Buildkite doesn't have this IIRC)
   - No 5MB Angular.js UI, the simpler and lighter the better
   - Doesn't burn CPU while idle like Travis

For BSD and Windows, a self-hosted solution is probably the most practical option. Azure's free offering might support WSL, but that's not clear yet.

Huge list of CI systems: https://github.com/ligurio/awesome-ci

The final solution might involve a combobulation of multiple systems, that is fine too. We just need comprehensive tests /and/ fast feedback tests.

**Comment by href** [comment]
I've had my eye on Buildkite for a while as the concept of "bring your own compute" appeals to me. But I haven't tried it yet. 

On another note, if you create a non-profit organisation as an umbrella for Mitogen you can get 5000$ worth of yearly Azure credits. I've done this in Switzerland for conference organisation and it was quite easy.

**Comment by kzap** [comment]
What about CircleCI?

> What if I am building open-source?
We offer a total of four free linux containers ($2400 annual value) for open-source projects. Simply keeping your project public will enable this for you!
> 
> We also offer the Seed plan free (at 1x concurrency) for OS X open source projects. Contact us at billing@circleci.com for access. If you are building a bigger open-source project and need more resources, let us know how we can help you!

**Comment by dw** [comment]
@kzap speed is the main problem! 4 jobs isn't enough, it's less than Travis.

Playing more with 'hypothetical nonexistent spot instances CI' system idea, assuming m1.small spot fleet and no contention, a single run of 144 jobs taking 5 minutes each comes out at $0.0528, or around 180 runs for $10. Google is about twice as expensive for preemptable instances, but they boot much faster

With a custom thing, it would be possible to bake in e.g. the test dependencies into the images, alongside a cache of the Docker images and suchlike, further reducing the runtime.

I really want to go this route, but haven't seen a system that would support it, and have no resource to write something, although it might be an awesome meta application for Mitogen, or perhaps an excellent addition to the examples/ directory.

**Comment by dw** [comment]
https://github.com/dw/mitogen/issues/410 needs CentOS + SELinux config

**Comment by yodatak** [comment]
Why not use a gitlab + Gitlab CI ?

**Comment by dw** [comment]
The hybrid Azure+Travis setup that exists now is working pretty great. Going to close this for the time being
