### ISSUE TITLE
DeprecationWarning: the imp module is deprecated

### ISSUE THREAD

**Issue by woopstar** [dw/mitogen#399]
Looks like the `imp` module is deprecated in favour of `importlib`

**Comment by dw** [comment]
Hi there,

Thanks for reporting this. Under what circumstances did you receive the deprecation message? Need to replace `imp`, but also need to remain compatible with older Pythons, so it's not a cutpaste switchover.

**Comment by dw** [comment]
This is now on the master branch and will make it into the next release. To be updated when a new release is made, subscribe to https://www.freelists.org/list/mitogen-announce

Thanks for reporting this!
