### ISSUE TITLE
remote execution

### ISSUE THREAD

**Issue by purpleidea** [dw/mitogen#41]
Hi, I saw your recent mitogen article, and then found this repo... You wrote:

> interested or have related ideas, please drop me an e-mail

I hope you don't mind that I decided to reach out over GH issue instead of email. Feel free to close this once you've read, or even if you've decide to ignore this completely :)

I started a project called mgmt: https://github.com/purpleidea/mgmt/

It has some different goals, but one of it's features is the ability to run in a manner similar to your tool:

https://ttboj.wordpress.com/2016/10/07/remote-execution-in-mgmt/

Here's a video, which includes a demonstration of the remote execution:

https://www.youtube.com/watch?v=LkEtBVLfygE&html5=1

If you're interested, feel free to get involved, and I'm certainly happy to help. I'm easily reachable as purpleidea on Freenode IRC in the #mgmtconfig channel.

One heads up: it's written in golang, not python. I used to be a major python user, but I decided golang was a better fit for this infrastructure tool.

One other small note: while we designed in the ability to "recursively" (your term) execute remotely, this particular feature isn't implemented yet, but is on the TODO list. The regular execution works well.

Good luck with your project!

**Comment by dw** [comment]
Hi!

Thanks for a link to your project, it really does look interesting, and I'm honestly excited by anything that moves the status quo for crappy devops tool forward :P  It looks a little larger in scope than what I'm aiming for, but I'll be watching it since you have tons of new ideas in there. Take care!

**Comment by MatthewHannigan** [comment]
FWIW I have a Google Doc with links to all sorts of config, automation and related tools.
If anyone is interested I could tidy it a bit and publish it.
It was born out of my frustrations with Puppet and Ansible.

**Comment by href** [comment]
@MatthewHannigan Please do!
