### ISSUE TITLE
Connection Delegation / delegate_to meta-ticket

### ISSUE THREAD

**Issue by dw** [dw/mitogen#412]
There are numerous issues with ansible_mitogen, delegate_to, and connection delegation just now:

* #340: delegate_to logic
* #369: delegate_to ignores --user
* #396: delegate_to incorrect python_path picked
* #401: connection delegation incorrect become password picked

Playing whack-a-mole with these is pointless, as the approach to selecting a connection configuration has no sound basis. Mitogen needs to emulate upstream Ansible, which handles only four cases:

* direct connection
* direct connection, become
* delegate_to
* delegate_to, become

But for connection delegation to work, Mitogen must also implement:

* delegated connection
* delegated connection, become
* delegated connection, delegate_to, become

Ansible derives the configuration from at least:

* `ansible.cfg` / `ansible.constants`
* `Plugin.get_option()`
* `Task`
* hostvars

Older versions simply reused all Ansible's configuration logic, however at some point, in an attempt to unify delegation + delegate_to, delegate_to was changed to custom logic. The result is the slew of bugs above.

Simultaneous to this, upstream has partially migrated configuration to per-plugin AnsiblePlugin.get_option(), which uses inline YAML to define data sources. Ideally a new approach would also move to get_option() where possible, although this may not be possible in order to maintain backwards compatibility with older Ansibles.

There is confusion in the existing code about where variables come from and where they should apply, and the relevant pieces are insufficiently documented causing further end user confusion.

**Comment by dw** [comment]
The first 4 cases work like they did in 0.2.2 again. Connection delegation issues will be fixed on an as-needed basis, although current master improves it significantly anyway.

**Comment by knightsg** [comment]
I can confirm this fixed my issue in #465.
