### ISSUE TITLE
On some shell script that start java cannot open shared object file: Too many open files

### ISSUE THREAD

**Issue by yodatak** [dw/mitogen#435]
Have you tried the latest master version from Git? Yes and 0.2.3
Centos 7.3 and RHEL 7.3
Python versions 2.7

In using some shell script that start some java i got some errors like this 
cannot open shared object file: Too many open files

 i try to run them with:
- name: Arret du node
  vars:
    mitogen_task_isolation: fork
  become: true
  become_user: "{{ user }}"
  shell: XXXXXXX

But i don't fix the issue is there is a solution for this ?

**Comment by jbeisser** [comment]
As a bypass, I've been invoking the client environment, and not using become if it can be avoided.

```
shell: sh -i -c "XXXXX"
```

**Comment by jbeisser** [comment]
I'm running from Python 2.7.13, with 2.6.6 on CentOS6 on remote systems. If there's an easy way to increase the FDs, or have the execution honor the system `ulimit` settings, I'm all ears. I'd rather not set the per module `mitogen_task_isolation`, to keep the playbooks fairly generic.

**Comment by dw** [comment]
@jbeisser the relevant code block appears on line 94 of ansible_mitogen/target.py. You can literally just delete that block and things will work as you desire. But per the original problem, this creates huge latency on default Red Hat installs.

**Comment by dw** [comment]
I've checked in a hopefully permanent fix on master. Would it be possible for you both to re-test?

Thanks again for reporting!

**Comment by yodatak** [comment]
Thanks for me it fix the problems i have !

**Comment by dw** [comment]
This is now on the master branch and will make it into the next release. To be updated when a new release is made, subscribe to https://www.freelists.org/list/mitogen-announce

Thanks for the confirmation and thanks again for reporting this!

**Comment by jbeisser** [comment]
Yep, ran a quick test against master. Works!
