### ISSUE TITLE
Zombie process test

### ISSUE THREAD

**Issue by dw** [dw/mitogen#482]
Following on from #480, this is a relatively frequently occurring problem, and it's always discovered by accident. Test suites should be updated to snapshot process list before / after test run, and fail if any stragglers exist.

- [x] Snapshot process list during setUpClass(), verify during teardownClass().
- [x] Snapshot process list before ./run_tests, ./mitogen_ansible_playbook etc, verify on complete
- [x] Snapshot target Docker container process list before / after ansible_tests run

Subprocess shutdown is asynchronous with regard to `broker.join()` right now, so at least initially this may need some nasty sleeps or retries to give the child a chance to go away on its own. It also bumps against #169 where the test suite does not reap processes reliably until process exit.

This may need to be done only for 'python' exes and 'mitogen:' comms, because e.g. DebOps may cause services to start in the container, and running tests on desktop while e.g. GNOME is doing stuff may cause flakeyness

Interesting comms/exes:

- [ ] python
- [ ] ssh
- [ ] mitogen:
- [ ] sudo
- [ ] su

**Comment by cloudnull** [comment]
Maybe related - https://github.com/dw/mitogen/issues/510#issuecomment-459937284

The processes were not zombies, but I did have a situation were there were hundreds of mitogen processes still up on a machine after a lot of runs. That said, this all could have been due to something I was hacking on. I need to circle back and see if I can make it happen again.

**Comment by dw** [comment]
I have gotten a bit sidetracked in the past week, but I found another case where they couldn't shut down due to the disconnect propagation work due in 0.2.4. The most recent change may be on master already, or still in my (currently very unhealthy) dmw branch.

This needs a more general fix. The problem in both recent cases was a crash during graceful shutdown. That procedure was historically bulletproof up to I think 0.2.3, and has gone downhill due to the disconnect propagation work.

IIRC what was happening last time was that the service thread pool was started up in the child, and that is what held the process alive after the broker thread crashed. What is supposed to happen is that as a final mea culpa, the broker thread kills the process right at the end of processing, to ensure absolutely nothing can leave anything behind. This might just need some blanket try/excepts in the appropriate places to ensure any broken callback or Stream.on_shutdown() cannot interrupt the shutdown process
