### ISSUE TITLE
PyPI sdist missing license

### ISSUE THREAD

**Issue by carlwgeorge** [dw/mitogen#538]
The BSD license requires distributing the copyright and license with the software.  However, [mitogen-0.2.4.tar.gz from PyPI](https://files.pythonhosted.org/packages/e0/7c/4bd35d8bee1acd649cd2653d46f12771eb3cfd72596a507293e86d4fd7d0/mitogen-0.2.4.tar.gz) is missing the LICENSE file.

**Comment by dw** [comment]
man, this gets me on every setup.py project all over again :) fix will be in 0.2.5 due end of week. Thanks for reporting!

**Comment by dw** [comment]
0.2.5 is on PyPI now :)

**Comment by carlwgeorge** [comment]
Thanks for the quick resolution!
