### ISSUE TITLE
fakessh.Process.wake() can never return on Python < 2.7

### ISSUE THREAD

**Issue by moreati** [dw/mitogen#55]
The function waits until `self.wake_event.wait(0.1)` returns `True`, wait_event is an instance of `threading.Event` https://github.com/dw/mitogen/blob/a8dcd53ccca0d6fffc4568bc216ddedeed610474/mitogen/fakessh.py#L162-L164

However in Python 2.6 and earlier [`Event.wait()`](https://docs.python.org/2.7/library/threading.html#threading.Event.wait) *always* returns `None`

> This method returns the internal flag on exit, so it will always return `True` except if a timeout is given and the operation times out.
>
> Changed in version 2.7: Previously, the method always returned `None`.

**Comment by moreati** [comment]
I see two possible fixes for this

1. Don't specify a timeout, and remove the while loop.
1. Something like
    ```python
            # NB: Before Python 2.7 threading.Event.wait() always returns None. 
            #     On Python 2.7+ it returns True, unless the timeout is reached.
            while not self.wake_event.wait(0.1) and not self.wake_event.isSet():
                pass
    ```

**Comment by dw** [comment]
Well spotted! Thanks again :)
