### ISSUE TITLE
WSL 2016 Anniversary Update tcsetattr() failure

### ISSUE THREAD

**Issue by dw** [dw/mitogen#550]
I think this problem might be back. I'm trying to run this on WSL using mitogen 2.5 with ansible 2.7.7 and getting the following during the Gather Facts step.

```
ERROR! [pid 17342] 16:05:31.543223 E mitogen: mitogen.service.Pool(0x7f089dd07c10, size=32, th='mitogen.service.Pool.7f089dd07c10.worker-0'): while invoking u'get' of u'ansible_mitogen.services.ContextService'
Traceback (most recent call last):
  File "/etc/ansible/mitogen-0.2.5/mitogen/service.py", line 544, in _on_service_call
    return invoker.invoke(method_name, kwargs, msg)
  File "/etc/ansible/mitogen-0.2.5/mitogen/service.py", line 274, in invoke
    response = self._invoke(method_name, kwargs, msg)
  File "/etc/ansible/mitogen-0.2.5/mitogen/service.py", line 260, in _invoke
    ret = method(**kwargs)
  File "/etc/ansible/mitogen-0.2.5/ansible_mitogen/services.py", line 467, in get
    reraise(*result)
  File "/etc/ansible/mitogen-0.2.5/ansible_mitogen/services.py", line 425, in _wait_or_start
    response = self._connect(key, spec, via=via)
  File "/etc/ansible/mitogen-0.2.5/ansible_mitogen/services.py", line 377, in _connect
    context = method(via=via, unidirectional=True, **spec['kwargs'])
  File "/etc/ansible/mitogen-0.2.5/mitogen/parent.py", line 2152, in ssh
    return self.connect(u'ssh', **kwargs)
  File "/etc/ansible/mitogen-0.2.5/mitogen/parent.py", line 2097, in connect
    **mitogen.core.Kwargs(kwargs))
  File "/etc/ansible/mitogen-0.2.5/mitogen/parent.py", line 2078, in _connect
    stream.connect()
  File "/etc/ansible/mitogen-0.2.5/mitogen/parent.py", line 1380, in connect
    self.pid, fd, diag_fd = self.start_child()
  File "/etc/ansible/mitogen-0.2.5/mitogen/parent.py", line 1354, in start_child
    return self.create_child(args, **self.create_child_args)
  File "/etc/ansible/mitogen-0.2.5/mitogen/parent.py", line 498, in hybrid_tty_create_child
    disable_echo(master_fd)
  File "/etc/ansible/mitogen-0.2.5/mitogen/parent.py", line 245, in disable_echo
    termios.tcsetattr(fd, flags, new)
error: (22, 'Invalid argument')
An exception occurred during task execution. To see the full traceback, use -vvv. The error was:     termios.tcsetattr(fd, flags, new)
```

_Originally posted by @zyphermonkey in https://github.com/dw/mitogen/issues/319#issuecomment-466549496_

**Comment by dw** [comment]
Hey @zyphermonkey. Can you please report exact WSL version and Python version.

WSL is a moving target, so possibly this is new breakage, or you simply haven't upgraded for a while

**Comment by dw** [comment]
I think WSL version is tied to OS build number -- see https://github.com/Microsoft/WSL/issues/1728#issuecomment-282566395

**Comment by zyphermonkey** [comment]
# uname -a
`Linux <hostname> 6 3.4.0+ #1 PREEMPT Thu Aug 1 17:06:05 CST 2013 x86_64 x86_64 x86_64 GNU/Linux`

# OS Build
`14393.2791`

# ansible --version
```
ansible 2.7.7
  config file = /root/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.6 (default, Nov 13 2018, 12:45:42) [GCC 4.8.4]
```

**Comment by dw** [comment]
Thanks. A little busy just now, but will spin up Windows VM later and try to figure this one out.

Just to confirm, was this definitely a "plain old" SSH connection? Any `become: true` or similar involved?

**Comment by zyphermonkey** [comment]
I tried it with and without `become: true` set and the error is the same either way.

I also tried an adhoc ping command with the same results.

**Comment by dw** [comment]
Thanks a ton for narrowing it down, it's definitely an SSH problem.

Just to confirm (probably true)

- this happens 100% of the time
- you can SSH to the machine normally otherwise

WSL is very funny about lifetimes and object states. For example if SSH client exitted quickly, and so nothing was left open on the TTY, maybe that could explain the error, but probably not

**Comment by zyphermonkey** [comment]
> * this happens 100% of the time

Yes it doesn't appear to matter what settings I chose it just fails immediately with this error.
> * you can SSH from WSL to the machine normally otherwise

I can ssh to the box with no issue from within WSL and if I'm not using mitogen everything works.

**Comment by dw** [comment]
It seems you're on the supposed "Redstone 1" release, aka 2016 Anniversary Update, whereas mine is "Redstone 4" aka. April 2018 update.

Do you know if your machine is particularly out of date for some reason? I'm really not familiar with Windows update cycles, so possibly this is a normal situation, perhaps a result of your corporate domain settings or similar.

The code is working fine for me locally. It seems I need to go digging in WSL's GitHub to figure out what may have broken/changed between those two releases.

I'm guessing a workaround should be more than possible -- these are very core UNIX APIs. It is likely WSL is objecting to some particular bit set in the value we supply, or similar

**Comment by dw** [comment]
Does strace work for you on that WSL install? If it does, running Ansible with a command line:

`strace -f -o /tmp/foo ansible-playbook .....` 

Followed by

`grep EINVAL /tmp/foo | tail -10`

Might reveal the exact system call and flag combination that is failing

**Comment by zyphermonkey** [comment]
strace appears to lockup bash. When I ctrl+c to break out of it I get this.

```
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/etc/ansible/mitogen-0.2.5/ansible_mitogen/process.py", line 181, in <lambda>
    atexit.register(lambda: clean_shutdown(cls.worker_sock))
  File "/etc/ansible/mitogen-0.2.5/ansible_mitogen/process.py", line 83, in clean_shutdown
    sock.recv(1)
KeyboardInterrupt
```

And here is the output from the strace.

```
# grep -i einval /tmp/ansible.trace
18    readlink("/usr/bin/python2.7", 0x7fffd10858f0, 4096) = -1 EINVAL (Invalid argument)
30    ioctl(76, SNDCTL_TMR_CONTINUE or SNDRV_TIMER_IOCTL_GPARAMS or TCSETSF, {B38400 -opost -isig -icanon -echo ...}) = -1 EINVAL (Invalid argument)
```

**Comment by dw** [comment]
Okay, I think I can see what's happening. You're right, it is exactly the old bug. The patch creates an `IS_WSL` variable, which I /think/ is set to `False` in your install, because the output of `uname` is different on these older versions.

Looks like https://github.com/Microsoft/WSL/issues/423#issuecomment-221627364 is how we're supposed to reliably detect WSL.

If possible, would you mind catting the contents of the files listed on that ticket:

* /proc/sys/kernel/osrelease
* /proc/version

I want to make sure fixing `IS_WSL` will work for modern and older versions. Thanks again!

**Comment by dw** [comment]
You can verify it's just a flag issue by editing `mitogen/core.py` and changing the `IS_WSL = ...` near line 143 to `IS_WSL = True`. The library should start working

**Comment by zyphermonkey** [comment]
cat /proc/sys/kernel/osrelease
`3.4.0-Microsoft`

cat /proc/version
`Linux version 3.4.0-Microsoft (Microsoft@Microsoft.com) (gcc version 4.7 (GCC) ) #1 SMP PREEMPT Wed Dec 31 14:42:53 PST 2014`

I also made the change to `mitogen/core.py` and still getting an error
```
ERROR! [pid 26] 09:59:44.868879 E mitogen: mitogen.service.Pool(0x7f98154e2f90, size=32, th='mitogen.service.Pool.7f98154e2f90.worker-0'): while invoking u'get' of u'ansible_mitogen.services.ContextService'
Traceback (most recent call last):
  File "/etc/ansible/mitogen-0.2.5/mitogen/service.py", line 544, in _on_service_call
    return invoker.invoke(method_name, kwargs, msg)
  File "/etc/ansible/mitogen-0.2.5/mitogen/service.py", line 274, in invoke
    response = self._invoke(method_name, kwargs, msg)
  File "/etc/ansible/mitogen-0.2.5/mitogen/service.py", line 260, in _invoke
    ret = method(**kwargs)
  File "/etc/ansible/mitogen-0.2.5/ansible_mitogen/services.py", line 467, in get
    reraise(*result)
  File "/etc/ansible/mitogen-0.2.5/ansible_mitogen/services.py", line 425, in _wait_or_start
    response = self._connect(key, spec, via=via)
  File "/etc/ansible/mitogen-0.2.5/ansible_mitogen/services.py", line 377, in _connect
    context = method(via=via, unidirectional=True, **spec['kwargs'])
  File "/etc/ansible/mitogen-0.2.5/mitogen/parent.py", line 2152, in ssh
    return self.connect(u'ssh', **kwargs)
  File "/etc/ansible/mitogen-0.2.5/mitogen/parent.py", line 2097, in connect
    **mitogen.core.Kwargs(kwargs))
  File "/etc/ansible/mitogen-0.2.5/mitogen/parent.py", line 2078, in _connect
    stream.connect()
  File "/etc/ansible/mitogen-0.2.5/mitogen/parent.py", line 1380, in connect
    self.pid, fd, diag_fd = self.start_child()
  File "/etc/ansible/mitogen-0.2.5/mitogen/parent.py", line 1354, in start_child
    return self.create_child(args, **self.create_child_args)
  File "/etc/ansible/mitogen-0.2.5/mitogen/parent.py", line 511, in hybrid_tty_create_child
    close_fds=True,
  File "/etc/ansible/mitogen-0.2.5/mitogen/parent.py", line 302, in detach_popen
    proc = subprocess.Popen(preexec_fn=preexec_fn, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
IOError: [Errno 1] Operation not permitted
An exception occurred during task execution. To see the full traceback, use -vvv. The error was:     raise child_exception
```

**Comment by dw** [comment]
Hrm! That's a new issue, and another ioctl() problem.

Would you mind changing `mitogen/parent.py` around line 377 from:

    if hasattr(termios, 'TIOCSCTTY'): 

to:

    if hasattr(termios, 'TIOCSCTTY') and not mitogen.core.IS_WSL: 

I think it is the only possible explanation for that failure

Thanks a ton for your help -- it really sucks I can't think of an easy way to test this locally. My Technet subscription expired :)

**Comment by zyphermonkey** [comment]
That worked. I had to keep the `IS_WSL = True` set in `mitogen/core.py` though so the check for that will need updated as well.

**Comment by dw** [comment]
Thanks a ton for this! Looks like I've got everything I need. Yay remote debugging :)

**Comment by dw** [comment]
Hi there,

Would you mind giving current master a test? It should be fixed now

**Comment by zyphermonkey** [comment]
Just tried the current master. It works with no errors. 👍

**Comment by dw** [comment]
Thanks so much!
