### ISSUE TITLE
Possible issue with python3 using virtualenvs and Docker?

### ISSUE THREAD

**Issue by dsgnr** [dw/mitogen#559]
I'm trying to use Mitogen within a Docker virtual environment. Docker container is Ubuntu 18. This issue does not seem to occur using python2.7 on an Ubuntu 18 virtual machine.

Dockerfile:

    RUN virtualenv /ansible27
    RUN . /ansible27/bin/activate; python3 -m pip install ansible==2.7.6 mitogen
    ENV ANSIBLE_STRATEGY=mitogen_linear

Within the container:

    root@e35c798bf514:/# . /ansible27/bin/activate
    (ansible27) root@e35c798bf514:/# pip3 list | egrep 'mitogen|ansible'
    ansible          2.7.6
    mitogen          0.2.6

    (ansible27) root@e35c798bf514:/#  ansible-config dump --only-changed
    ANSIBLE_NOCOWS(/etc/ansible/ansible.cfg) = True
    ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = False
    ANSIBLE_SSH_ARGS(/etc/ansible/ansible.cfg) = -o ControlMaster=yes -o ControlPersist=yes -F /root/.ssh/config
    ANSIBLE_SSH_CONTROL_PATH(/etc/ansible/ansible.cfg) = ~/.ssh/master-%%r@%%h:%%p
    DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 9
    DEFAULT_SCP_IF_SSH(/etc/ansible/ansible.cfg) = True
    DEFAULT_STRATEGY(env: ANSIBLE_STRATEGY) = mitogen_linear
    DEFAULT_TRANSPORT(/etc/ansible/ansible.cfg) = ssh
    HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
    RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False

    (ansible27) root@e35c798bf514:/# ansible localhost -m setup -vvv
    ansible 2.7.6
    config file = /etc/ansible/ansible.cfg
    configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
    ansible python module location = /ansible27/lib/python3.6/site-packages/ansible
    executable location = /ansible27/bin/ansible
    python version = 3.6.7 (default, Oct 22 2018, 11:32:17) [GCC 8.2.0]
    Using /etc/ansible/ansible.cfg as config file
    /etc/ansible/hosts did not meet host_list requirements, check plugin documentation if this is unexpected
    Skipping due to inventory source not existing or not being readable by the current user
    /etc/ansible/hosts did not meet script requirements, check plugin documentation if this is unexpected
    Skipping due to inventory source not existing or not being readable by the current user
    /etc/ansible/hosts did not meet yaml requirements, check plugin documentation if this is unexpected
    Skipping due to inventory source not existing or not being readable by the current user
    /etc/ansible/hosts did not meet ini requirements, check plugin documentation if this is unexpected
    /etc/ansible/hosts did not meet auto requirements, check plugin documentation if this is unexpected
    [WARNING]: Unable to parse /etc/ansible/hosts as an inventory source

    [WARNING]: No inventory was parsed, only implicit localhost is available

    [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

    ERROR! Invalid play strategy specified: mitogen_linear

I'm not sure whether this is bug related, but going by step 3 https://mitogen.readthedocs.io/en/latest/ansible.html#installation it would appear that this is possible.

Using a normal environment with python2.7 (not Docker) this is working fine so just wanted to see whether this output is expected, and whether I'm incorrect somewhere.

Thanks in advance for any advice/pointers!

**Comment by dsgnr** [comment]
So.. looks like i was being a bit silly!

```    ANSIBLE_STRATEGY_PLUGINS=/ansible27/lib/python3.6/site-packages/ansible_mitogen/plugins/strategy
``` was required within the Dockerfile. Would it be useful for the docs linked above be updated with the fact that `ANSIBLE_STRATEGY_PLUGINS` needs to be called also?

Thanks!!

**Comment by dw** [comment]
I tried adding this and I don't like the result -- it pushes BS config choices on the user, I'd rather remove BS choices :)

The real answer to this is likely to be Ansible Collections when it is ready. It should allow use of a well-known command for activating the plugin

Thanks again for reporting
