### ISSUE TITLE
Upload a working version to pypi

### ISSUE THREAD

**Issue by MoritzFago** [dw/mitogen#56]
Currently you can do `pip install mitogen`, this will pretend to install the library, but actualy doesn't install anything. There should be some warning or errror, instead of just doing a fake install.

**Comment by dw** [comment]
Hi Moritz!

Thanks for taking a look :)  I'm going to leave this bug open, but for now I don't really want a version of PyPI.. there are huge bits missing that might require API changes that would be harder once people are depending on it. :/

Unfortunately PyPI removed the ability to register a package without uploading it. There was no way to reserve the name without a dummy package upload. Perhaps I could make a dummy setup.py that exits with an error and upload that instead

**Comment by MoritzFago** [comment]
I think the dummy, that prints a explaination of the situation would be great. Also this would be
1. Documented
2. self-explainatory

**Comment by dw** [comment]
Given that I'm running this code 5 or 6 times a week as part of a commercial app, I think it's stupid to continue considering it alpha quality ;)  I've pushed a working version to PyPI

**Comment by kedare** [comment]
I agree, it could be interestring to have it in PYPI, it's currently there but it's missing the `ansible_mitogen` directory.

**Comment by dw** [comment]
Hi @kedare. I just checked the PyPI version:

````
$ pip download mitogen
Collecting mitogen
  Using cached https://files.pythonhosted.org/packages/d3/9b/5f44ae787c29f809c7fa5a6369c3795afe3699266c1669da29917bb916ca/mitogen-0.2.6.tar.gz
  Saved ./mitogen-0.2.6.tar.gz
Successfully downloaded mitogen

$ tar ztf mitogen-0.2.6.tar.gz
mitogen-0.2.6/ansible_mitogen/
mitogen-0.2.6/ansible_mitogen/loaders.py
mitogen-0.2.6/ansible_mitogen/logging.py
mitogen-0.2.6/ansible_mitogen/plugins/
mitogen-0.2.6/ansible_mitogen/plugins/strategy/
mitogen-0.2.6/ansible_mitogen/plugins/strategy/mitogen_linear.py
...
````

It looks like it's all there. What method are you using to install it?
