### ISSUE TITLE
0.2.6 not available as tag

### ISSUE THREAD

**Issue by gertvdijk** [dw/mitogen#563]
I noticed version 0.2.6 is available on https://mitogen.readthedocs.io/en/latest/ansible.html, but not as tag or release in the repository (latest I see is `v0.2.5`). Could you please tag it appropriately? (Perhaps just forgot to push the tags?) Thanks!

**Comment by dw** [comment]
Great catch! It's because I was rushing to respond to a ticket just after uploading the tarballs :) Thanks for letting me know
