### ISSUE TITLE
"No such process" exception during shutdown of forked process

### ISSUE THREAD

**Issue by dw** [dw/mitogen#573]
I believe I am experiencing this issue..

```
ERROR! [mux  28528] 09:47:10.844462 E mitogen.ctx.ssh.host: mitogen: mitogen.fork.Stream('fork.13988') crashed
Traceback (most recent call last):
  File "<stdin>", line 2959, in _call
  File "<stdin>", line 1629, in on_receive
  File "master:/home/david/git/pcon/ansible/mitogen-0.2.6/mitogen/parent.py", line 1290, in on_disconnect
    self._reap_child()
  File "master:/home/david/git/pcon/ansible/mitogen-0.2.6/mitogen/parent.py", line 1280, in _reap_child
    os.kill(self.pid, signal.SIGTERM)
ProcessLookupError: [Errno 3] No such process
ERROR! [mux  28528] 09:47:10.854249 E mitogen.ctx.ssh.host2: mitogen: mitogen.fork.Stream('fork.17372') crashed
Traceback (most recent call last):
  File "<stdin>", line 2959, in _call
  File "<stdin>", line 1629, in on_receive
  File "master:/home/david/git/pcon/ansible/mitogen-0.2.6/mitogen/parent.py", line 1290, in on_disconnect
    self._reap_child()
  File "master:/home/david/git/pcon/ansible/mitogen-0.2.6/mitogen/parent.py", line 1280, in _reap_child
    os.kill(self.pid, signal.SIGTERM)
ProcessLookupError: [Errno 3] No such process
```

I am on 0.2.6

_Originally posted by @DavidVentura in https://github.com/dw/mitogen/pull/318#issuecomment-476530535_

**Comment by dw** [comment]
Hi David,

What version of Python is on the target machine, and when does this error occur? Was it mid-run, during shutdown, or when running a particular module? etc.

All this code has been replaced in a branch that will land soon, but it would be still good to understand how you're seeing it at all.

**Comment by dw** [comment]
The fact this happened on 2 hosts means it is unlikely to be a race condition, but some kind of logic error.

The fact the child process does not exist means that some code running in the remote interpreter has either

- a) installed a SIGCHLD handler with SIG_IGN, which causes child processes to recycle as soon as they exit, or
- b) installed a custom SIGCHLD handler which called waitpid() on our process

I'm thinking a) is a more likely explanation..

Can you please include a list of modules being executed.

Are you running any custom modules?

**Comment by DavidVentura** [comment]
Hey,
Both machines run on python3.6, the error occurred at shutdown. I use no custom modules.. just `copy, file, template, uri, fail`

**Comment by dw** [comment]
This has started manifesting on the Azure Python 3.5 build job.

Finally seeing it printed in a terminal font something obvious is noticeable -- the `atexit` handler appears to running twice.

**Comment by dw** [comment]
Hi @DavidVentura, I'm going to close this as the code in question has been entirely rewritten on current master. If you are still experiencing the issue, please don't hesitate to reopen.

The rewritten implementation relies on the standard Python subprocess module to manage the child, custom PID waiting logic has been (in this case) completely removed.

The previous comment was incorrect, the waitpid() call in that case is completely different.

Thanks a ton for reporting this, and apologies for the delay in replying.
