### ISSUE TITLE
GitHub issue template contains broken link?

### ISSUE THREAD

**Issue by thbar** [dw/mitogen#574]
The template to create issues links to:

https://mitogen.rtfd.io/en/stable/ansible.html#common-problems

but if I understand well, the correct link would be:

https://mitogen.networkgenomics.com/ansible_detailed.html#common-problems

If that's correct hit me up and I'll prepare a quick PR.

**Comment by dw** [comment]
Thanks a ton for reporting this -- I've bundled it into the #575 branch, because CI is so slow :)
