### ISSUE TITLE
Mitogen Ansible : "Failed to get information on remote file" when plugin executes modules and 'become' is used

### ISSUE THREAD

**Issue by PieterVoet** [dw/mitogen#580]
Please drag-drop large logs as text file attachments.

Feel free to write an issue in your preferred format, however if in doubt, use
the following checklist as a guide for what to include.

* Which version of Ansible are you running?
* Is your version of Ansible patched in any way?
* Are you running with any custom modules, or `module_utils` loaded?

* Have you tried the latest master version from Git?
* Do you have some idea of what the underlying problem may be?
  https://mitogen.networkgenomics.com/ansible_detailed.html#common-problems has
  instructions to help figure out the likely cause and how to gather relevant
  logs.
* Mention your host and target OS and versions
* Mention your host and target Python versions
* If reporting a performance issue, mention the number of targets and a rough
  description of your workload (lots of copies, lots of tiny file edits, etc.)
* If reporting a crash or hang in Ansible, please rerun with -vvv and include
  200 lines of output around the point of the error, along with a full copy of
  any traceback or error text in the log. Beware "-vvv" may include secret
  data! Edit as necessary before posting.
* If reporting any kind of problem with Ansible, please include the Ansible
  version along with output of "ansible-config dump --only-changed".

**Comment by PieterVoet** [comment]
Using Mitogen Ansible fails when using mitogen as a strategy plugin if :
 - 'become' is used to 'switch user' to a non-root remote user, either through the playbook of setting the play_context variables
 - some module is executed before the Copy task executes the 'task' module. Here, the 'file' module is used to create a remote directory
 - the Copy task is called

The testcase runs fine if :
  - mitogen is not used as a strategy plugin
  - either 'become' or the 'file' module is omitted from the testcase
  - the 'mitogen_task_isolation' variable is set to 'fork'

* Which version of Ansible are you running?
  (ansible-2.6.2) [voetp02@il7p0006 ansible]$ ansible --version
ansible 2.6.2
  config file = /home/ISL/voetp02/ansible/ansible.cfg
  configured module search path = [u'/home/ISL/voetp02/ansible/modules']
  ansible python module location = /opt/pythonenvs/ansible-2.6.2/lib/python2.7/site-packages/ansible
  executable location = /opt/pythonenvs/ansible-2.6.2/bin/ansible
  python version = 2.7.11 (default, Aug  9 2018, 11:22:25) [GCC 4.4.7 20120313 (Red Hat 4.4.7-18)]

* Is your version of Ansible patched in any way?
No

* Are you running with any custom modules, or `module_utils` loaded?
Yes. Playbook, module and action plugin will be attached

* Mention your host and target OS and versions
  Host : Red Hat Enterprise Linux Server release 6.9 (Santiago)
  Target : Red Hat Enterprise Linux Server release 6.9 (Santiago)

* Mention your host and target Python versions
  Host : Python 2.7.11
  Target : Python 2.6.6

(ansible-2.6.2) [voetp02@il7p0006 ansible]$ ansible-config dump --only-changed
ANSIBLE_FORCE_COLOR(/home/ISL/voetp02/ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(env: ANSIBLE_SSH_ARGS) =
DEFAULT_ACTION_PLUGIN_PATH(/home/ISL/voetp02/ansible/ansible.cfg) = [u'/home/ISL/voetp02/ansible/plugins/action']
DEFAULT_CALLBACK_PLUGIN_PATH(/home/ISL/voetp02/ansible/ansible.cfg) = [u'/home/ISL/voetp02/ansible/plugins/callback']
DEFAULT_CALLBACK_WHITELIST(/home/ISL/voetp02/ansible/ansible.cfg) = ['profile_tasks', 'timer']
DEFAULT_FILTER_PLUGIN_PATH(/home/ISL/voetp02/ansible/ansible.cfg) = [u'/home/ISL/voetp02/ansible/plugins/filter']
DEFAULT_HOST_LIST(/home/ISL/voetp02/ansible/ansible.cfg) = [u'/home/ISL/voetp02/ansible/inventories/IPAS.inventory']
DEFAULT_LOG_PATH(/home/ISL/voetp02/ansible/ansible.cfg) = /home/ISL/voetp02/ansible/logs/ansible.log
DEFAULT_LOOKUP_PLUGIN_PATH(/home/ISL/voetp02/ansible/ansible.cfg) = [u'/home/ISL/voetp02/ansible/plugins/lookup']
DEFAULT_MODULE_PATH(/home/ISL/voetp02/ansible/ansible.cfg) = [u'/home/ISL/voetp02/ansible/modules']
DEFAULT_PRIVATE_KEY_FILE(/home/ISL/voetp02/ansible/ansible.cfg) = /home/ISL/voetp02/.ssh/ansible_rsa
DEFAULT_REMOTE_USER(/home/ISL/voetp02/ansible/ansible.cfg) = ansible
DEFAULT_ROLES_PATH(/home/ISL/voetp02/ansible/ansible.cfg) = [u'/home/ISL/voetp02/ansible/roles']
DEFAULT_STDOUT_CALLBACK(/home/ISL/voetp02/ansible/ansible.cfg) = bcie_stdout
DEFAULT_STRATEGY(/home/ISL/voetp02/ansible/ansible.cfg) = mitogen_linear
DEFAULT_STRATEGY_PLUGIN_PATH(/home/ISL/voetp02/ansible/ansible.cfg) = [u'/opt/pythonenvs/ansible-2.6.2/lib/python2.7/site-packages/ansible_mitogen/plugins/strategy']
HOST_KEY_CHECKING(/home/ISL/voetp02/ansible/ansible.cfg) = False
RETRY_FILES_ENABLED(/home/ISL/voetp02/ansible/ansible.cfg) = False

**Comment by PieterVoet** [comment]
[ansible_run.txt](https://github.com/dw/mitogen/files/3079569/ansible_run.txt)

**Comment by PieterVoet** [comment]
Wrong button

**Comment by PieterVoet** [comment]
[pvtest_actionplugin.py.txt](https://github.com/dw/mitogen/files/3079579/pvtest_actionplugin.py.txt)
[pvtest.yml.txt](https://github.com/dw/mitogen/files/3079581/pvtest.yml.txt)
[pvtest.py.txt](https://github.com/dw/mitogen/files/3079582/pvtest.py.txt)
[ansible_run.txt](https://github.com/dw/mitogen/files/3079591/ansible_run.txt)
[mitogen.81923.20190415_105324.log](https://github.com/dw/mitogen/files/3079595/mitogen.81923.20190415_105324.log)
[mitogen.81920.20190415_105324.log](https://github.com/dw/mitogen/files/3079596/mitogen.81920.20190415_105324.log)
[mitogen.81811.20190415_105323.log](https://github.com/dw/mitogen/files/3079597/mitogen.81811.20190415_105323.log)
[mitogen.81802.20190415_105322.log](https://github.com/dw/mitogen/files/3079598/mitogen.81802.20190415_105322.log)

**Comment by PieterVoet** [comment]
Hi,
excuse me, but I'm wondering if I reported this issue correctly..   I can see newer issues get commented on by the author, but this issue appears sort of unnoticed..
Thanks.

**Comment by dw** [comment]
Hi Pieter,

Unfortunately I'm not working on Mitogen full time any more, and only have occasional time to contribute. And yes, it's just me ;)  Tickets are done according to how much investigation they need -- order they were filed in is of little relevance.

Thanks so much for the detailed report here. I will hopefully get to it in the coming days

**Comment by PieterVoet** [comment]
Hi David,
 
thanks for your update, and good luck figuring ou what's going on.
Have a nice day !
 
Pieter.
Thanks & regards, Pieter VoetIBM SWG WebSphere services, the NetherlandsTel: (+31)20-5132041 GSM: 06-53412985 Internet: PieterVoet@nl.ibm.com
 
 
----- Original message -----From: dw <notifications@github.com>To: dw/mitogen <mitogen@noreply.github.com>Cc: PieterVoet <pietervoet@nl.ibm.com>, State change <state_change@noreply.github.com>Subject: Re: [dw/mitogen] Mitogen Ansible : "Failed to get information on remote file" when plugin executes modules and 'become' is used (#580)Date: Sat, May 11, 2019 5:47 PM 
Hi Pieter,
Unfortunately I'm not working on Mitogen full time any more, and only have occasional time to contribute. And yes, it's just me ;) Tickets are done according to how much investigation they need -- order they were filed in is of little relevance.
Thanks so much for the detailed report here. I will hopefully get to it in the coming days
—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.
 Tenzij hierboven anders aangegeven: / Unless stated otherwise above:
IBM Nederland B.V.
Gevestigd te Amsterdam
Inschrijving Handelsregister Amsterdam Nr. 33054214

**Comment by dw** [comment]
Hi Pieter,

My apologies for the extreme delay in replying to such a well constructed report :)

I have investigated some of this, and it looks like it may possibly be two separate issues:

- the supplied example action plugin is using Python's import mechanism to load the copy action. This prevents Mitogen's patches from overriding the default ActionModule implementation during loading.

Instead of:

````python
from ansible.plugins.action.copy import ActionModule as Copy
...
Copy(...).run()
````

You should write:

````python
try:
    # Ansible >= 2.4
    from ansible.plugins.loader import action_loader
except ImportError:
    # Ansible < 2.4
    from ansible.plugins import action_loader

copy_action = action_loader.get('copy', ...)
# Mitogen ActionMixin also requires access to task_vars, so it must be forwareded.
result = copy_action.run(task_vars=task_vars)
````

The second part, where you are seeing similar problems when running simply as a module, that is likely due to #582, where Mitogen's temp file lifetimes differ subtly from upstream's. I have not yet reproduced this second part, so perhaps it is a completely different issue.

Thanks again for reporting this

**Comment by PieterVoet** [comment]
Hi David,
 
thanks for your reply !  great !
I'll make your suggested change first thing tomorrow and let you know !
 
Have a nice day !Thanks & regards, Pieter VoetIBM SWG WebSphere services, the NetherlandsTel: (+31)20-5132041 GSM: 06-53412985 Internet: PieterVoet@nl.ibm.com
 
 
----- Original message -----From: dw <notifications@github.com>To: dw/mitogen <mitogen@noreply.github.com>Cc: PieterVoet <pietervoet@nl.ibm.com>, State change <state_change@noreply.github.com>Subject: [EXTERNAL] Re: [dw/mitogen] Mitogen Ansible : "Failed to get information on remote file" when plugin executes modules and 'become' is used (#580)Date: Mon, Jun 3, 2019 4:05 PM 
Hi Pieter,
My apologies for the extreme delay in replying to such a well constructed report :)
I have investigated some of this, and it looks like it may possibly be two separate issues:
        the supplied example action plugin is using Python's import mechanism to load the copy action. This prevents Mitogen's patches from overriding the default ActionModule implementation during loading.
Instead of:
from ansible.plugins.action.copy import ActionModule as Copy...Copy(...).run()
You should write:
try:    # Ansible >= 2.4    from ansible.plugins.loader import action_loaderexcept ImportError:    # Ansible < 2.4    from ansible.plugins import action_loadercopy_action = action_loader.get('copy', ...)# Mitogen ActionMixin also requires access to task_vars, so it must be forwareded.result = copy_action.run(task_vars=task_vars)
The second part, where you are seeing similar problems when running simply as a module, that is likely due to #582, where Mitogen's temp file lifetimes differ subtly from upstream's. I have not yet reproduced this second part, so perhaps it is a completely different issue.
Thanks again for reporting this
—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.
 Tenzij hierboven anders aangegeven: / Unless stated otherwise above:
IBM Nederland B.V.
Gevestigd te Amsterdam
Inschrijving Handelsregister Amsterdam Nr. 33054214

**Comment by PieterVoet** [comment]
Hi David,
 
I can confirm that applying your suggestions to my code resolved the problem !
Great ! Thanks so much for your time spent on this so far.
 
I'm not sure if I coded my plugin illegally.. I think I studied sources of an early
Ansible release and copied it. But your modification uses loader object methods
which I think is cleaner. 
I'll close the issue.
 
Thanks & have a nice day !
 
Thanks & regards, Pieter VoetIBM SWG WebSphere services, the NetherlandsTel: (+31)20-5132041 GSM: 06-53412985 Internet: PieterVoet@nl.ibm.com
 
 
----- Original message -----From: dw <notifications@github.com>To: dw/mitogen <mitogen@noreply.github.com>Cc: PieterVoet <pietervoet@nl.ibm.com>, State change <state_change@noreply.github.com>Subject: [EXTERNAL] Re: [dw/mitogen] Mitogen Ansible : "Failed to get information on remote file" when plugin executes modules and 'become' is used (#580)Date: Mon, Jun 3, 2019 4:05 PM 
Hi Pieter,
My apologies for the extreme delay in replying to such a well constructed report :)
I have investigated some of this, and it looks like it may possibly be two separate issues:
        the supplied example action plugin is using Python's import mechanism to load the copy action. This prevents Mitogen's patches from overriding the default ActionModule implementation during loading.
Instead of:
from ansible.plugins.action.copy import ActionModule as Copy...Copy(...).run()
You should write:
try:    # Ansible >= 2.4    from ansible.plugins.loader import action_loaderexcept ImportError:    # Ansible < 2.4    from ansible.plugins import action_loadercopy_action = action_loader.get('copy', ...)# Mitogen ActionMixin also requires access to task_vars, so it must be forwareded.result = copy_action.run(task_vars=task_vars)
The second part, where you are seeing similar problems when running simply as a module, that is likely due to #582, where Mitogen's temp file lifetimes differ subtly from upstream's. I have not yet reproduced this second part, so perhaps it is a completely different issue.
Thanks again for reporting this
—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.
 Tenzij hierboven anders aangegeven: / Unless stated otherwise above:
IBM Nederland B.V.
Gevestigd te Amsterdam
Inschrijving Handelsregister Amsterdam Nr. 33054214

**Comment by dw** [comment]
I would prefer to just use the import mechanism too, but Ansible's module loading logic really does not match the import mechanism at all. For example, it is possible for the user to override the standard 'copy' module, and for that overridden implementation to be loaded in memory at `ansible.plugins.action.copy`, and it is possible for roles to extend the search path such that `action_loader` will populate `sys.modules["ansible.plugins.action.myaction"]` with in-memory modules that never exist as part of that package on disk.

The modules you find in ansible/modules/ and ansible/plugins/ in the Ansible source tree can't really be treated like Python packages at all, more like nested directories that just happen to reflect the in-memory structure in the default configuration.

Hope this helps
