### ISSUE TITLE
Mitogen leaks local host information to remote host

### ISSUE THREAD

**Issue by polski-g** [dw/mitogen#581]
While running ansible using mitogen as the strategy_plugin, if you look at the process listing on the remote host (`ps auxw`) you can see the connecting host username and connecting host name in the process list.

Assuming your local username is LUSER and local host name is LHOST, you would see the following in the remote host process listing:

```
ps auxw|grep mitogen
root 17053 ... 0:01 /usr/bin/python(mitogen:LUSER@LHOST:29900)
```

Can this information be obfuscated in some way?

**Comment by dw** [comment]
Yes. It is a very simple option to add, it's just nobody had previously asked for it. The default is there to help admins figure out what's causing a problem. Thanks for reporting this

**Comment by dw** [comment]
There is a new mitogen_mask_remote_name variable. You can get it anywhere convenient (mostly likeely inventory host or group) and it'll cause processes to identify as "python(mitogen:ansible)". Let me know if you have any trouble :)

------

This is now on the master branch and will make it into the next release. To be updated when a new release is made, subscribe to https://www.freelists.org/list/mitogen-announce

Thanks for reporting this!
