### ISSUE TITLE
mitogen.service.call not available

### ISSUE THREAD

**Issue by ghp-rr** [dw/mitogen#589]
In samples found on the net, e.g. 
https://mitogen.networkgenomics.com/services.html
there is a call to  

mitogen.service.call(context, FileService.handle, {
        'path': path
    })

In mitogen 0.2.6, this 'call' is not available.

**Comment by dw** [comment]
Hi there, thanks for reporting this. The core library documentation is terrible at present. If you are playing with it, it might be worth scanning the docs TODO list on https://github.com/dw/mitogen/issues/451 for further hints.

I've updated the example on the services page to ensure it runs, and removed the very outdated files from the examples directory.
