### ISSUE TITLE
Investigate alerts found by lgtm.com

### ISSUE THREAD

**Issue by moreati** [dw/mitogen#61]
[LGTM](https://lgtm.com) is a service that performs static and dynamic code analysis. It can find potential bugs such as use of uninitialized variables, or iteration over types that don't support it.

The initial scan has found [11 Alerts](https://lgtm.com/projects/g/dw/mitogen/alerts/?mode=list). These should be investigated, then fixed or silenced as appropriate.

**Comment by dw** [comment]
Better late than never :)
