### ISSUE TITLE
Ansible fetch from target do not use streaming file transfer

### ISSUE THREAD

**Issue by dw** [dw/mitogen#615]
I think we've hit this issue.
```
2019-07-08 21:42:27,015 p=22109 u=root |  TASK [lms-support : Gather host support information] ***************************
2019-07-08 21:42:27,015 p=22109 u=root |  Monday 08 July 2019  21:42:27 +0000 (0:00:00.250)       0:00:11.641 ***********
2019-07-08 21:42:27,359 p=22109 u=root |  included: /opt/exabeam_installer/ansible/roles/lms/lms-support/tasks/run_support_on_host.yml for host1, host2
2019-07-08 21:42:27,479 p=22109 u=root |  TASK [lms-support : set_fact] **************************************************
2019-07-08 21:42:27,479 p=22109 u=root |  Monday 08 July 2019  21:42:27 +0000 (0:00:00.463)       0:00:12.105 ***********
2019-07-08 21:42:27,579 p=22109 u=root |  ok: [host1]
2019-07-08 21:42:27,596 p=22109 u=root |  ok: [host2]
2019-07-08 21:42:27,706 p=22109 u=root |  TASK [lms-support : Run support task on hosts] *********************************
2019-07-08 21:42:27,707 p=22109 u=root |  Monday 08 July 2019  21:42:27 +0000 (0:00:00.227)       0:00:12.333 ***********
2019-07-08 21:43:18,005 p=22109 u=root |  changed: [host2]
2019-07-08 21:43:47,972 p=22109 u=root |  changed: [host1]
2019-07-08 21:43:48,088 p=22109 u=root |  TASK [lms-support : Fetch output tar file] *************************************
2019-07-08 21:43:48,089 p=22109 u=root |  Monday 08 July 2019  21:43:48 +0000 (0:01:20.381)       0:01:32.715 ***********
2019-07-08 21:43:49,344 p=22109 u=root |  changed: [host2]
2019-07-08 21:43:54,815 p=22109 u=root |  ERROR! [task 29315] 21:43:54.814786 E mitogen: Maximum message size exceeded (got 218211706, max 134217728)
```

The task that triggered this was:
```
- name: Fetch output tar file
  fetch: dest="{{ support_root_dir }}/" src="{{ output_file }}" flat=yes
  ignore_errors: yes
```

Despite the `ignore_errors: yes`, ansible exited/crashed here.

Interestingly, the size of the file that it was trying to transfer was 163658638 bytes (~157MiB), not 218211706 bytes.

`host1` is the local host running ansible, but connected over SSH.

_Originally posted by @alexhexabeam in https://github.com/dw/mitogen/issues/279#issuecomment-509757108_

**Comment by dw** [comment]
Hi @alexhexabeam,

Your problem is slightly different -- download is not done with streaming transfer. The `max_message_size` limit is a sanity check, the protocol should never be coping with messages anywhere nearly that large, as they trigger memory spikes on every machine.

This is a problem of missing functionality in the extension -- uploads are already streaming, but downloads are still message-based. This was just never added because I forgot about it, and nobody complained.. until now.. :)

Thanks for reporting this, it should be a very quick fix, so will hopefully include it in 0.2.8

**Comment by dw** [comment]
The reason for the size expansion is almost certainly due to a horrible misfeature of Python 3 -- documented in #485. Are you using Python 3 on the controller or target?

A fix for that is much more involved. If you have SSH compression enabled (which is the default with Mitogen), this size expansion should almost completely disappear in terms of bandwidth usage.

**Comment by alexhexabeam** [comment]
@dw Thanks for the attention on this.

We are using Python 2.7.5 (the one that ships with CentOS 7) on both, so it's unlikely to be caused by a Python 3 issue.

Our ansible.cfg is as follows:
```
[defaults]
any_errors_fatal=True
ask_sudo_pass=False
callback_whitelist=profile_tasks
deprecation_warnings=False
forks=32
gather_timeout=60
hash_behavior=merge
host_key_checking=False
jinja2_extensions = jinja2.ext.do
log_path=../ansible.log
pipelining=True
retry_files_enabled=False
roles_path=roles/plt:roles/lms:roles/uba:roles/soar
timeout = 90
strategy_plugins = mitogen-master/ansible_mitogen/plugins/strategy
strategy = mitogen_linear

[ssh_connection]
# ControlPersist 5 hours
retries=5
ssh_args = -o ControlMaster=auto -o ControlPersist=18000s -o ForwardAgent=yes

[privilege_escalation]
become = True
become_method = sudo

[callback_profile_tasks]
task_output_limit = 10
```

**Comment by dw** [comment]
Are both your controller and target machines on Python 2? The originator of the message would cause the size expansion -- in the case of file download, it's be the target machine. If it is not in fact Python 3, then that is verrry interesting, and requires further investigation

**Comment by dw** [comment]
The size expansion is almost exactly 33%, so it definitely looks like the same issue as #485

**Comment by dw** [comment]
Sorry, I see you wrote "on both": ) Apologies, I wasn't doubting your answer, just not reading it

**Comment by alexhexabeam** [comment]
We are definitely using Python 2.7.5 on both. RedHat (and in turn CentOS) backports all kinds of things, though, so maybe they grabbed some change that they shouldn't have.

We have had mitogen disabled since we hit this, so we may have had a slightly older RPM at the time. Our current package is python-2.7.5-76.el7.x86_64

**Comment by dw** [comment]
This is now on the master branch and will make it into the next release. To be updated when a new release is made, subscribe to https://networkgenomics.com/mail/mitogen-announce/

Thanks for reporting this!

**Comment by alexhexabeam** [comment]
@dw This does not seem to be fixed.

This is easily reproducible by creating a 512MB file, then attempting to fetch it. I tested this with both compressible and uncompressible data.

I created the files on the remote machine (host2 in this example):
```
dd if=/dev/urandom of=/opt/exabeam/data/urandomtest bs=1M count=512
dd if=/dev/zero of=/opt/exabeam/data/zerotest bs=1M count=512
```

Then ran this playbook:
```
- name: test
  any_errors_fatal: True
  hosts: host2
  gather_facts: no
  become: yes
  become_method: sudo
  tasks:
    - name: fetch urandomtest
      fetch:
        src: /opt/exabeam/data/urandomtest
        dest: /tmp/
        flat: yes
    - name: fetch zerotest
      fetch:
        src: /opt/exabeam/data/zerotest
        dest: /tmp/
        flat: yes
```

Note that it hung after the error until I CTRL-C'd it after several minutes.
```
(.env) [exabeam@dev-20190816-233324-1 ansible]$ ansible-playbook -i ../inventory playbooks/test.yml

PLAY [test] **************************************************************************************************************************************************************************************************************************************************************************************************************************************************

TASK [fetch urandomtest] *************************************************************************************************************************************************************************************************************************************************************************************************************************************************
Saturday 17 August 2019  00:04:21 +0000 (0:00:00.299)       0:00:00.299 *******
ERROR! [task 11477] 00:04:40.856360 E mitogen: Maximum message size exceeded (got 715828094, max 134217728)
^CProcess WorkerProcess-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
 [ERROR]: User interrupted execution

    self.run()
  File "/opt/exabeam_installer/ansible/mitogen/ansible_mitogen/strategy.py", line 174, in wrap_worker__run
    lambda: worker__run(self)
  File "/opt/exabeam_installer/ansible/mitogen/mitogen/core.py", line 633, in _profile_hook
    return func(*args)
  File "/opt/exabeam_installer/ansible/mitogen/ansible_mitogen/strategy.py", line 174, in <lambda>
    lambda: worker__run(self)
  File "/opt/exabeam_installer/.env/lib/python2.7/site-packages/ansible/executor/process/worker.py", line 118, in run
    self._final_q
  File "/opt/exabeam_installer/.env/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 140, in run
    res = self._execute()
  File "/opt/exabeam_installer/.env/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 612, in _execute
    result = self._handler.run(task_vars=variables)
  File "/opt/exabeam_installer/ansible/mitogen/ansible_mitogen/mixins.py", line 116, in run
    return super(ActionModuleMixin, self).run(tmp, task_vars)
  File "/opt/exabeam_installer/.env/lib/python2.7/site-packages/ansible/plugins/action/fetch.py", line 95, in run
    slurpres = self._execute_module(module_name='slurp', module_args=dict(src=source), task_vars=task_vars)
  File "/opt/exabeam_installer/ansible/mitogen/ansible_mitogen/mixins.py", line 359, in _execute_module
    timeout_secs=self.get_task_timeout_secs(),
  File "/opt/exabeam_installer/ansible/mitogen/ansible_mitogen/planner.py", line 503, in invoke
    kwargs=planner.get_kwargs(),
  File "/opt/exabeam_installer/ansible/mitogen/ansible_mitogen/connection.py", line 445, in call
    return self._rethrow(recv)
  File "/opt/exabeam_installer/ansible/mitogen/ansible_mitogen/connection.py", line 431, in _rethrow
    return recv.get().unpickle()
  File "/opt/exabeam_installer/ansible/mitogen/mitogen/core.py", line 1177, in get
    msg = self._latch.get(timeout=timeout, block=block)
  File "/opt/exabeam_installer/ansible/mitogen/mitogen/core.py", line 2637, in get
    return self._get_sleep(poller, timeout, block, rsock, wsock, cookie)
  File "/opt/exabeam_installer/ansible/mitogen/mitogen/core.py", line 2654, in _get_sleep
    woken = list(poller.poll(timeout))
  File "/opt/exabeam_installer/ansible/mitogen/mitogen/parent.py", line 936, in _poll
    events, _ = mitogen.core.io_op(self._pollobj.poll, timeout)
  File "/opt/exabeam_installer/ansible/mitogen/mitogen/core.py", line 553, in io_op
    return func(*args), None
KeyboardInterrupt
```

The behavior is the same for the /dev/urandom data as for the /dev/zero data.

**Comment by alexhexabeam** [comment]
Some more details about our environment:

We are using the system python, but have a virtualenv with several modules.
```
(.env) [exabeam@dev-20190816-233324-1 ansible]$ rpm -qa | grep python
python-ipaddress-1.0.16-2.el7.noarch
audit-libs-python-2.8.4-4.el7.x86_64
python2-rsa-3.4.1-1.el7.noarch
python-google-compute-engine-2.8.14-1.el7.noarch
python-decorator-3.4.0-3.el7.noarch
python-urlgrabber-3.10-9.el7.noarch
dbus-python-1.1.1-9.el7.x86_64
libxml2-python-2.9.1-6.el7_2.3.x86_64
python-six-1.9.0-2.el7.noarch
python-chardet-2.2.1-1.el7_1.noarch
python-backports-1.0-8.el7.x86_64
python-setuptools-0.9.8-7.el7.noarch
python-urllib3-1.10.2-5.el7.noarch
python2-boto-2.45.0-3.el7.noarch
libsemanage-python-2.5-14.el7.x86_64
python-IPy-0.75-6.el7.noarch
policycoreutils-python-2.5-29.el7_6.1.x86_64
python-libs-2.7.5-77.el7_6.x86_64
python-slip-0.4.0-4.el7.noarch
python-linux-procfs-0.4.9-4.el7.noarch
python-schedutils-0.4-6.el7.x86_64
python-configobj-4.7.2-7.el7.noarch
python-gobject-base-3.22.0-1.el7_4.1.x86_64
python-pycurl-7.19.0-19.el7.x86_64
python-jsonpatch-1.2-4.el7.noarch
python-prettytable-0.7.2-3.el7.noarch
python-jinja2-2.7.2-3.el7_6.noarch
python-slip-dbus-0.4.0-4.el7.noarch
python-kitchen-1.1.1-5.el7.noarch
python-pyudev-0.15-9.el7.noarch
python-perf-3.10.0-957.12.1.el7.x86_64
rpm-python-4.11.3-35.el7.x86_64
python2-pyasn1-0.1.9-7.el7.noarch
python-backports-ssl_match_hostname-3.5.0.1-1.el7.noarch
python-requests-2.6.0-1.el7_1.noarch
python-2.7.5-77.el7_6.x86_64
newt-python-0.52.15-4.el7.x86_64
libselinux-python-2.5-14.1.el7.x86_64
python-iniparse-0.4-9.el7.noarch
python-markupsafe-0.11-10.el7.x86_64
python-jsonpointer-1.9-2.el7.noarch
python-babel-0.9.6-8.el7.noarch
python-firewall-0.5.3-5.el7.noarch
```

```
(.env) [exabeam@dev-20190816-233324-1 ansible]$ pip freeze
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
ansible==2.7.11
asn1crypto==0.24.0
backports.ssl-match-hostname==3.5.0.1
bcrypt==3.1.4
cffi==1.11.5
click==6.7
cryptography==2.3.1
docker-py==1.6.0
docopt==0.6.1
elasticsearch==6.2.0
enum34==1.1.6
Fabric==1.14.0
Flask==1.0.2
funcsigs==1.0.2
gevent==1.3.4
greenlet==0.4.13
idna==2.7
ipaddress==1.0.18
itsdangerous==0.24
Jinja2==2.10
MarkupSafe==0.23
marshmallow==3.0.0rc5
mock==2.0.0
parallel-ssh==1.6.3
paramiko==2.4.1
pbr==4.0.4
pem==18.1.0
pyasn1==0.4.3
pycparser==2.18
pyhocon==0.3.31
pymongo==3.6.0
PyNaCl==1.2.1
pyOpenSSL==18.0.0
pyparsing==2.2.0
python-dateutil==2.4.2
PyYAML==3.12
requests==2.9.1
six==1.10.0
ssh2-python==0.14.0
urllib3==1.22
websocket-client==0.35.0
Werkzeug==0.14.1
```

**Comment by alexhexabeam** [comment]
This was with mitogen 93c97a9564a54b602f660adadff4cc12ffa3763c

**Comment by dw** [comment]
Ansible's `fetch` action plug-in internally resorts to using the `slurp` module internally when `become` is active, presumably to work around filesystem permission problems since they can't sudo from an SFTP session.

This means your 512mb test file is getting base64-encoded and held in memory on the controller and the target. What a joke

Let me keep this one open, I might just reimplement `fetch` since it's a straightforward module.

**Comment by alexhexabeam** [comment]
@dw Thanks for the quick response. I've confirmed that we only hit this with `become` active.

**Comment by dw** [comment]
This also explains the strange 33% size increase 'bug' we saw before. It's base64 encoding. For a 512mb file, Ansible will read the whole 512mb into a string then base64-encode it. The base64-encoded string is then JSON-serialized to go in the task output.

Looking at `slurp.py`, both string references are still alive at exit, along with the JSON representation, so a 512mb copy will cause a **1.83 GiB** memory usage spike on both machines.

The library is supposed to send 'dead messages' to the intended receiver when a message is dropped due to its size being exceeded, either it was never implemented or there is some problem with the implementation. So that's a separate bug, your run should not have hung.

It's possible to increase the message size limit, but that does not solve anything, it just kicks the can down the road, and makes similar problems like this one harder to spot. It's tempting to perhaps update the limit to 1 GiB or similar, but again this solution does not sit well with me.

As a more general solution to every situation where Ansible might pull something like this, really we want huge module outputs to be streamed just like file transfer. I might open a separate ticket for that

**Comment by dw** [comment]
Your example playbook is now working on 'dmw' branch. It may take a few days to reach master, but this will be in 0.2.8.

Runtime to copy both files drops from 47 seconds to 6.7 seconds. I think we can call this a win.

Note if you're copying huge files like this, you almost certainly want `mitogen_ssh_compression: false` in group vars

**Comment by dw** [comment]
@alexhexabeam Please reopen if somehow this still doesn't work, but become+fetch has its own test now. All the best

**Comment by alexhexabeam** [comment]
I've confirmed the above playbook works great with Mitogen v0.2.8. Memory usage during the transfer stays stable regardless of the file size (tested with up to 20GB).

Thanks again for your great support, and for making this excellent tool.
