### ISSUE TITLE
RFC: Use unittest2 for tests?

### ISSUE THREAD

**Issue by moreati** [dw/mitogen#64]
David, do you have any preference on adding [unttest2](https://pypi.python.org/pypi/unittest2) as a dev dependency? It would allow using the newer `assert*` methods in tests (e.g. `assertTrue`, `assertIsInstance`) to make tests more descriptive and test failure messages more helpful.

Alternatives:

- Use pytest as the test runner, and use plain assert statements.
- Selectively backport/copy from unittest2 into mitogen's own `testlib.TestCase`

**Comment by dw** [comment]
Your call :)  I like py.test, but especially when debugging hangs and suchlike in a library like this one, its machinery tends to get in the way of simply getting a useful stack trace, or sticking a few debug statements in near the top of the stack (e.g. to trigger a timed signal etc), so I do not like to require py.test.

unittest2, I guess it's fairly harmless, so it's your call :)  No to py.test requirement, maybe/yes to unittest2!
