### ISSUE TITLE
Should Stream._connect_bootstrap() return anything?

### ISSUE THREAD

**Issue by moreati** [dw/mitogen#67]
I noticed that `mitogen.master.Stream._connect_bootstrap()` doesn't return anything. However the subclasses (`mitogen.ssh.Stream`, and `mitogen.sudo.Stream`) _do_ return the result of `self._ec0_received()`

Since `mitogen.master.Stream._ec0_received()` also doesn't return anything, I think this discrepancy has no material impact and I assume the return statements are harmless leftovers from some earlier stage of mitogen. Does this sound right?

**Comment by dw** [comment]
Sounds about right! I had a nasty old habit years ago of combining "return" with the last line of the block if it was possible, but as you can tell, it's confusing to people reading the code.. feel free to clean up this kind of thing when you see it, and assume original developer was simply being a dolt ;)
