### ISSUE TITLE
Fails to perform docker pull via ansible

### ISSUE THREAD

**Issue by lonix1** [dw/mitogen#718]
### HOST

- Ubuntu 19.10
- Ansible 2.9.9 (latest)
- Mitogen 0.2.9 (latest)
- Python 3.7.5
- `ansible-config dump --only-changed` yields an empty file
- Nothing custom

### TARGET
- Ubuntu 18.04
- Python ? There are multiple versions on the target machine, so I ran `ansible -m setup machinename` and it showed me `"ansible_python_version": "2.7.17"`. I hope that's right?

### PROBLEM
In a playbook:
````yml
- name: pull image
  docker_image:
    name: imagename:v1.2.3
    source: pull
````

Error:
>"msg": "Failed to import the required Python library (Docker SDK for Python: docker (Python >= 2.7) or docker-py (Python 2.6)) on remote's Python /usr/bin/python. Please read module documentation and install in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter, for example via `pip install docker` or `pip install docker-py` (Python 2.6). The error was: u'requests' is present in the Mitogen importer blacklist, therefore this context will not attempt to request it from the master, as the request will always be refused."

This is part of a very large playbook which seems to work, only this task fails. And without mitogen this task works.

I have no idea what the problem could be?

**Comment by s1113950** [comment]
Can you try with latest Mitogen from `master`? It includes ansible python interpreter discovery and some other things

**Comment by lonix1** [comment]
@s1113950 That worked... thanks!! 😄 

1. It was muuuuuuuuuch slower during initial connection/setup/whatever - is that normal? Is that because of the "python interpreter autodiscovery"?

2. Can I use it in production? If not, when do you think it'll get released?

3. I unzipped the master zip from github, and used it as is. But I'm not a python dev... Do I need to compile/build/whatever to make it go faster?

**Comment by s1113950** [comment]
Woo!!
The interpreter discovery does add a tiny bit of overhead, but I haven't noticed drastic slowness on my end 🤔 definitely something I'll look into. Do you have a playbook I can use to repro?

You can use it in production, or wait for a new release(s) which will happen around the time Ansible 2.10 comes out. No PR lands currently in `master` without passing tests, so it should be stable enough for production, but I can't guarantee there won't be a regression missed (like a slower startup time that wasn't noticed before).

To install, you can do something like this into your venv: `pip install git+https://github.com/dw/mitogen`

**Comment by lonix1** [comment]
@s1113950 I don't have something easy to repro sorry, but I can live with the delay... it takes time to get started, but after that it zips through my playbook like a bullet train! 😃

I asked about the build step, because in the latest official release I have a `mitogen.egg-info` directory, whereas when I cloned the `master` branch I don't have that. It seems to work though as is.

Thanks again!

**Comment by s1113950** [comment]
Perf on Python3 is not yet as good as Python2, but eventually the plan is to fix that up 👍

**Comment by danielporto** [comment]
I still have this problem. Any plan when will the new release be available??

**Comment by s1113950** [comment]
A new release is planned for after Ansible 2.10 is released. There might be two, 1 (backwards-incompatible) with collections support and 1 without, depending on how big of a change collections support will be. See this thread if curious: #715

**Comment by s1113950** [comment]
There's a new rc now for Ansible 2.10+: https://github.com/dw/mitogen/releases/tag/v0.3.0-rc.0

**Comment by mickaelperrin** [comment]
I am still having this issue with mitogen 0.3.2. Any idea ?
