### ISSUE TITLE
Timeouts in test.sh obscure deadlocks

### ISSUE THREAD

**Issue by moreati** [dw/mitogen#96]
All test cases run by `test.sh` are wrapped by a call to [timeout(1)](https://linux.die.net/man/1/timeout). Cases where the process is forcefully terminated due to reaching the timeout are not reported. This is leading to errors passing silently.

**Comment by dw** [comment]
Huh, this was already partially covered by e48b6ca7f49cf4c524f83acf3246242ac4389202, but that script is missing "set -e", or anything that would ensure the failure is passed back to Travis. Hacked a minimal solution for now, reopen if this doesn't help
