### ISSUE TITLE
Clarification: Should Importer blacklist __builtin__ or __builtins__

### ISSUE THREAD

**Issue by moreati** [dw/mitogen#98]
`mitogen.core.Importer.blacklist` is initilialised to include two default items https://github.com/dw/mitogen/blob/49d944340d27829aa94776f0d4133623bade2607/mitogen/core.py#L416-L422

Is `__builtin__` (singular) correct? It seems at odds with the `__builtins__` (plural) object that a fresh CPython initialises.

**Comment by dw** [comment]
We loves our 2.x warts!

````
>>> import sys
>>>
>>>
>>> sys.modules['__builtin__']
<module '__builtin__' (built-in)>
>>>
>>> __builtins__
<module '__builtin__' (built-in)>
>>>
>>> sys.modules['__builtin__'] is __builtins__
True
````
